//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Abstrakcyjny typ zapytania. Inne zapytania z obowi¹zkowymi rolami dziedzicz¹ po nim cechy.
 *             
 * 
 * <p>Java class for BaseRequestWithRoles complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseRequestWithRoles">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseRequest">
 *       &lt;sequence>
 *         &lt;element name="roles" type="{http://playmobile.pl/pc/types}Roles"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseRequestWithRoles", propOrder = {
    "roles"
})
@XmlSeeAlso({
    GetOfferServices2 .class,
    GetRetentionOffers2 .class,
    GetMigrationProcessesWithOffers.class,
    GetUpsellOffers.class,
    GetUsageInfoOperation.class,
    GetRetentionStatusAndOffers2 .class,
    GetOffersRequest.class,
    GetRetentionStatusAndOffers.class,
    GetAllOffersRequest.class,
    GetPhoneInfos.class,
    BaseGetOffers.class
})
public abstract class BaseRequestWithRoles
    extends BaseRequest
{

    @XmlElement(required = true)
    protected Roles roles;

    /**
     * Gets the value of the roles property.
     * 
     * @return
     *     possible object is
     *     {@link Roles }
     *     
     */
    public Roles getRoles() {
        return roles;
    }

    /**
     * Sets the value of the roles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Roles }
     *     
     */
    public void setRoles(Roles value) {
        this.roles = value;
    }

}
