//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Zbiór us³ug CFS dla danej oferty
 * 
 * <p>Java class for CFSServices2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFSServices2">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cfsService" type="{http://playmobile.pl/pc/types}CFS2" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="section" use="required" type="{http://playmobile.pl/pc/types}CFSServiceSection" />
 *       &lt;attribute name="sectionId" use="required" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="selectMin" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="selectMax" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFSServices2", propOrder = {
    "cfsService"
})
public class CFSServices2 {

    @XmlElement(required = true)
    protected List<CFS2> cfsService;
    @XmlAttribute(name = "section", required = true)
    protected CFSServiceSection section;
    @XmlAttribute(name = "sectionId", required = true)
    protected long sectionId;
    @XmlAttribute(name = "selectMin")
    protected Long selectMin;
    @XmlAttribute(name = "selectMax")
    protected Long selectMax;

    /**
     * Gets the value of the cfsService property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cfsService property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCfsService().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CFS2 }
     * 
     * 
     */
    public List<CFS2> getCfsService() {
        if (cfsService == null) {
            cfsService = new ArrayList<CFS2>();
        }
        return this.cfsService;
    }

    /**
     * Gets the value of the section property.
     * 
     * @return
     *     possible object is
     *     {@link CFSServiceSection }
     *     
     */
    public CFSServiceSection getSection() {
        return section;
    }

    /**
     * Sets the value of the section property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFSServiceSection }
     *     
     */
    public void setSection(CFSServiceSection value) {
        this.section = value;
    }

    /**
     * Gets the value of the sectionId property.
     * 
     */
    public long getSectionId() {
        return sectionId;
    }

    /**
     * Sets the value of the sectionId property.
     * 
     */
    public void setSectionId(long value) {
        this.sectionId = value;
    }

    /**
     * Gets the value of the selectMin property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSelectMin() {
        return selectMin;
    }

    /**
     * Sets the value of the selectMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSelectMin(Long value) {
        this.selectMin = value;
    }

    /**
     * Gets the value of the selectMax property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getSelectMax() {
        return selectMax;
    }

    /**
     * Sets the value of the selectMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setSelectMax(Long value) {
        this.selectMax = value;
    }

}
