//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFSServiceSection.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CFSServiceSection">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="GROUPED_SERVICES"/>
 *     &lt;enumeration value="GROUPED_SERVICES_BENEFIT"/>
 *     &lt;enumeration value="TRANSITIVE_SERVICES"/>
 *     &lt;enumeration value="MUST_BE_SERVICES"/>
 *     &lt;enumeration value="OPTIONAL_SERVICES"/>
 *     &lt;enumeration value="REQUIRED_SERVICES"/>
 *     &lt;enumeration value="OPTIONAL_SERVICES_VAS"/>
 *     &lt;enumeration value="GROUPED_SERVICES_VAS"/>
 *     &lt;enumeration value="HIDDEN_SERVICES"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CFSServiceSection")
@XmlEnum
public enum CFSServiceSection {


    /**
     * Grupa us³ug opcjonalnych dla Taryfy w danej ofercie
     * 
     */
    GROUPED_SERVICES,

    /**
     * Sekcja pogrupowanych uslug opcjonalnych (wybor 1 z wielu) - Benefit
     *                     
     * 
     */
    GROUPED_SERVICES_BENEFIT,

    /**
     * Sekcja us³ug przechodz¹cych
     *                     
     * 
     */
    TRANSITIVE_SERVICES,

    /**
     * Grupa us³ug obligatoryjnych na poziomie CCBS
     * 
     */
    MUST_BE_SERVICES,

    /**
     * Grupa us³ug opcjonalnych na poziomie CCBS
     * 
     */
    OPTIONAL_SERVICES,

    /**
     * Grupa us³ug obligatoryjnych biznesowo na poziomie CCBS
     * 
     */
    REQUIRED_SERVICES,

    /**
     * Sekcja us³ug opcjonalnych VAS
     * 
     */
    OPTIONAL_SERVICES_VAS,

    /**
     * Sekcja us³ug do wyboru VAS
     * 
     */
    GROUPED_SERVICES_VAS,

    /**
     * Sekcja us³ug domyœlnie niewidocznych
     * 
     */
    HIDDEN_SERVICES;

    public String value() {
        return name();
    }

    public static CFSServiceSection fromValue(String v) {
        return valueOf(v);
    }

}
