//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFSType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CFSType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BILLING"/>
 *     &lt;enumeration value="BILLING_ACCOUNT"/>
 *     &lt;enumeration value="BILLING_PARAM"/>
 *     &lt;enumeration value="BILLING_TARRIF_DISC"/>
 *     &lt;enumeration value="BILLING_MEMBER"/>
 *     &lt;enumeration value="BILLING_OWNER"/>
 *     &lt;enumeration value="BILLING_PARTICULAR_ANNEX_ONLY"/>
 *     &lt;enumeration value="MNP_PREPAID"/>
 *     &lt;enumeration value="M_AND_M"/>
 *     &lt;enumeration value="C_PLUS"/>
 *     &lt;enumeration value="VIRTUAL"/>
 *     &lt;enumeration value="BUSINESS_PACKET"/>
 *     &lt;enumeration value="BILLING_TRY_AND_BUY"/>
 *     &lt;enumeration value="BILLING_RECHARGE"/>
 *     &lt;enumeration value="BILLING_OTB"/>
 *     &lt;enumeration value="VAS"/>
 *     &lt;enumeration value="VAS_OUT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CFSType")
@XmlEnum
public enum CFSType {

    BILLING,
    BILLING_ACCOUNT,
    BILLING_PARAM,
    BILLING_TARRIF_DISC,
    BILLING_MEMBER,
    BILLING_OWNER,
    BILLING_PARTICULAR_ANNEX_ONLY,
    MNP_PREPAID,
    M_AND_M,
    C_PLUS,
    VIRTUAL,
    BUSINESS_PACKET,
    BILLING_TRY_AND_BUY,
    BILLING_RECHARGE,
    BILLING_OTB,
    VAS,
    VAS_OUT;

    public String value() {
        return name();
    }

    public static CFSType fromValue(String v) {
        return valueOf(v);
    }

}
