//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * odpowiedü zawierajπca vanity, reason, fee oraz cfs'y
 * 
 * <p>Java class for FeeElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeeElement">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cfs" type="{http://playmobile.pl/pc/types}CFS2" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="vanity" type="{http://playmobile.pl/pc/types}VanityName" />
 *       &lt;attribute name="reason" type="{http://playmobile.pl/pc/types}Reason" />
 *       &lt;attribute name="feeAmount" type="{http://playmobile.pl/pc/types}Amount" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeeElement", propOrder = {
    "cfs"
})
public class FeeElement {

    protected CFS2 cfs;
    @XmlAttribute(name = "vanity")
    protected VanityName vanity;
    @XmlAttribute(name = "reason")
    protected Reason reason;
    @XmlAttribute(name = "feeAmount")
    protected BigDecimal feeAmount;

    /**
     * Gets the value of the cfs property.
     * 
     * @return
     *     possible object is
     *     {@link CFS2 }
     *     
     */
    public CFS2 getCfs() {
        return cfs;
    }

    /**
     * Sets the value of the cfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFS2 }
     *     
     */
    public void setCfs(CFS2 value) {
        this.cfs = value;
    }

    /**
     * Gets the value of the vanity property.
     * 
     * @return
     *     possible object is
     *     {@link VanityName }
     *     
     */
    public VanityName getVanity() {
        return vanity;
    }

    /**
     * Sets the value of the vanity property.
     * 
     * @param value
     *     allowed object is
     *     {@link VanityName }
     *     
     */
    public void setVanity(VanityName value) {
        this.vanity = value;
    }

    /**
     * Gets the value of the reason property.
     * 
     * @return
     *     possible object is
     *     {@link Reason }
     *     
     */
    public Reason getReason() {
        return reason;
    }

    /**
     * Sets the value of the reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reason }
     *     
     */
    public void setReason(Reason value) {
        this.reason = value;
    }

    /**
     * Gets the value of the feeAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFeeAmount() {
        return feeAmount;
    }

    /**
     * Sets the value of the feeAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFeeAmount(BigDecimal value) {
        this.feeAmount = value;
    }

}
