//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu s³u¿¹cy do pobrania ofert w procesach migracyjnych
 * 
 * <p>Java class for GetMigrationProcessesWithOffers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetMigrationProcessesWithOffers">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseRequestWithRoles">
 *       &lt;attribute name="offerFromId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="recommendedTariffId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="recommendedTariffName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ccbsPromotionFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="tariffFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="ccbsTariffFromId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="salesChannelFrom" type="{http://playmobile.pl/pc/types}SalesChannel" />
 *       &lt;attribute name="processTypeFrom" type="{http://playmobile.pl/pc/types}ProcessType" />
 *       &lt;attribute name="ccbsPackageFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="segmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subSegmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clientLegalType" type="{http://www.w3.org/2001/XMLSchema}long" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetMigrationProcessesWithOffers")
public class GetMigrationProcessesWithOffers
    extends BaseRequestWithRoles
{

    @XmlAttribute(name = "offerFromId")
    protected Long offerFromId;
    @XmlAttribute(name = "recommendedTariffId")
    protected String recommendedTariffId;
    @XmlAttribute(name = "recommendedTariffName")
    protected String recommendedTariffName;
    @XmlAttribute(name = "ccbsPromotionFromId")
    protected Long ccbsPromotionFromId;
    @XmlAttribute(name = "tariffFromId")
    protected Long tariffFromId;
    @XmlAttribute(name = "ccbsTariffFromId")
    protected String ccbsTariffFromId;
    @XmlAttribute(name = "salesChannelFrom")
    protected SalesChannel salesChannelFrom;
    @XmlAttribute(name = "processTypeFrom")
    protected ProcessType processTypeFrom;
    @XmlAttribute(name = "ccbsPackageFromId")
    protected Long ccbsPackageFromId;
    @XmlAttribute(name = "segmentName")
    protected String segmentName;
    @XmlAttribute(name = "subSegmentName")
    protected String subSegmentName;
    @XmlAttribute(name = "clientLegalType")
    protected Long clientLegalType;

    /**
     * Gets the value of the offerFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferFromId() {
        return offerFromId;
    }

    /**
     * Sets the value of the offerFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferFromId(Long value) {
        this.offerFromId = value;
    }

    /**
     * Gets the value of the recommendedTariffId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendedTariffId() {
        return recommendedTariffId;
    }

    /**
     * Sets the value of the recommendedTariffId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendedTariffId(String value) {
        this.recommendedTariffId = value;
    }

    /**
     * Gets the value of the recommendedTariffName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendedTariffName() {
        return recommendedTariffName;
    }

    /**
     * Sets the value of the recommendedTariffName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendedTariffName(String value) {
        this.recommendedTariffName = value;
    }

    /**
     * Gets the value of the ccbsPromotionFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPromotionFromId() {
        return ccbsPromotionFromId;
    }

    /**
     * Sets the value of the ccbsPromotionFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPromotionFromId(Long value) {
        this.ccbsPromotionFromId = value;
    }

    /**
     * Gets the value of the tariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTariffFromId() {
        return tariffFromId;
    }

    /**
     * Sets the value of the tariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTariffFromId(Long value) {
        this.tariffFromId = value;
    }

    /**
     * Gets the value of the ccbsTariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffFromId() {
        return ccbsTariffFromId;
    }

    /**
     * Sets the value of the ccbsTariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffFromId(String value) {
        this.ccbsTariffFromId = value;
    }

    /**
     * Gets the value of the salesChannelFrom property.
     * 
     * @return
     *     possible object is
     *     {@link SalesChannel }
     *     
     */
    public SalesChannel getSalesChannelFrom() {
        return salesChannelFrom;
    }

    /**
     * Sets the value of the salesChannelFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesChannel }
     *     
     */
    public void setSalesChannelFrom(SalesChannel value) {
        this.salesChannelFrom = value;
    }

    /**
     * Gets the value of the processTypeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessType }
     *     
     */
    public ProcessType getProcessTypeFrom() {
        return processTypeFrom;
    }

    /**
     * Sets the value of the processTypeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessType }
     *     
     */
    public void setProcessTypeFrom(ProcessType value) {
        this.processTypeFrom = value;
    }

    /**
     * Gets the value of the ccbsPackageFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPackageFromId() {
        return ccbsPackageFromId;
    }

    /**
     * Sets the value of the ccbsPackageFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPackageFromId(Long value) {
        this.ccbsPackageFromId = value;
    }

    /**
     * Gets the value of the segmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentName() {
        return segmentName;
    }

    /**
     * Sets the value of the segmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentName(String value) {
        this.segmentName = value;
    }

    /**
     * Gets the value of the subSegmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSegmentName() {
        return subSegmentName;
    }

    /**
     * Sets the value of the subSegmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSegmentName(String value) {
        this.subSegmentName = value;
    }

    /**
     * Gets the value of the clientLegalType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientLegalType() {
        return clientLegalType;
    }

    /**
     * Sets the value of the clientLegalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientLegalType(Long value) {
        this.clientLegalType = value;
    }

}
