//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu s³u¿¹cy do pobrania oferty akwizycynej
 * 
 * <p>Java class for GetMigrationOffers2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetMigrationOffers2">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseGetOffers">
 *       &lt;attribute name="processType" use="required" type="{http://playmobile.pl/pc/types}ProcessType" />
 *       &lt;attribute name="msisdn" use="required" type="{http://playmobile.pl/pc/types}MSISDN" />
 *       &lt;attribute name="materialCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clientLegalType" type="{http://playmobile.pl/pc/types}ClientLegalType" />
 *       &lt;attribute name="ccbsTariffFromId" type="{http://playmobile.pl/pc/types}TariffId" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetMigrationOffers2")
public class GetMigrationOffers2
    extends BaseGetOffers
{

    @XmlAttribute(name = "processType", required = true)
    protected ProcessType processType;
    @XmlAttribute(name = "msisdn", required = true)
    protected String msisdn;
    @XmlAttribute(name = "materialCode")
    protected String materialCode;
    @XmlAttribute(name = "clientLegalType")
    protected Long clientLegalType;
    @XmlAttribute(name = "ccbsTariffFromId")
    protected String ccbsTariffFromId;

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessType }
     *     
     */
    public ProcessType getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessType }
     *     
     */
    public void setProcessType(ProcessType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the materialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * Sets the value of the materialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialCode(String value) {
        this.materialCode = value;
    }

    /**
     * Gets the value of the clientLegalType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientLegalType() {
        return clientLegalType;
    }

    /**
     * Sets the value of the clientLegalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientLegalType(Long value) {
        this.clientLegalType = value;
    }

    /**
     * Gets the value of the ccbsTariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffFromId() {
        return ccbsTariffFromId;
    }

    /**
     * Sets the value of the ccbsTariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffFromId(String value) {
        this.ccbsTariffFromId = value;
    }

}
