//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Request operacji getOfferDetails
 * 
 * <p>Java class for GetOfferDetailsRequest2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetOfferDetailsRequest2">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}AbstractRequestWithRoles">
 *       &lt;sequence>
 *         &lt;element name="rfsId" type="{http://playmobile.pl/pc/types}RfsId" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="processType" type="{http://playmobile.pl/pc/types}ProcessType" />
 *       &lt;attribute name="salesChannel" type="{http://playmobile.pl/pc/types}SalesChannel" />
 *       &lt;attribute name="offerId" use="required" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="voucherId" type="{http://playmobile.pl/pc/types}VoucherId" />
 *       &lt;attribute name="feature" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="clientLegalType" type="{http://playmobile.pl/pc/types}ClientLegalType" />
 *       &lt;attribute name="showHiddenCfs" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetOfferDetailsRequest2", propOrder = {
    "rfsId"
})
public class GetOfferDetailsRequest2
    extends AbstractRequestWithRoles
{

    protected List<RfsId> rfsId;
    @XmlAttribute(name = "processType")
    protected ProcessType processType;
    @XmlAttribute(name = "salesChannel")
    protected SalesChannel salesChannel;
    @XmlAttribute(name = "offerId", required = true)
    protected long offerId;
    @XmlAttribute(name = "voucherId")
    protected String voucherId;
    @XmlAttribute(name = "feature")
    protected String feature;
    @XmlAttribute(name = "clientLegalType")
    protected Long clientLegalType;
    @XmlAttribute(name = "showHiddenCfs")
    protected Boolean showHiddenCfs;

    /**
     * Gets the value of the rfsId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rfsId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRfsId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RfsId }
     * 
     * 
     */
    public List<RfsId> getRfsId() {
        if (rfsId == null) {
            rfsId = new ArrayList<RfsId>();
        }
        return this.rfsId;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessType }
     *     
     */
    public ProcessType getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessType }
     *     
     */
    public void setProcessType(ProcessType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the salesChannel property.
     * 
     * @return
     *     possible object is
     *     {@link SalesChannel }
     *     
     */
    public SalesChannel getSalesChannel() {
        return salesChannel;
    }

    /**
     * Sets the value of the salesChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesChannel }
     *     
     */
    public void setSalesChannel(SalesChannel value) {
        this.salesChannel = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     */
    public long getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     */
    public void setOfferId(long value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the voucherId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherId() {
        return voucherId;
    }

    /**
     * Sets the value of the voucherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherId(String value) {
        this.voucherId = value;
    }

    /**
     * Gets the value of the feature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFeature() {
        return feature;
    }

    /**
     * Sets the value of the feature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFeature(String value) {
        this.feature = value;
    }

    /**
     * Gets the value of the clientLegalType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientLegalType() {
        return clientLegalType;
    }

    /**
     * Sets the value of the clientLegalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientLegalType(Long value) {
        this.clientLegalType = value;
    }

    /**
     * Gets the value of the showHiddenCfs property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowHiddenCfs() {
        return showHiddenCfs;
    }

    /**
     * Sets the value of the showHiddenCfs property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowHiddenCfs(Boolean value) {
        this.showHiddenCfs = value;
    }

}
