//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for GetOffersRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetOffersRequest">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseRequestWithRoles">
 *       &lt;attribute name="offerId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="processType" type="{http://playmobile.pl/pc/types}ProcessType" />
 *       &lt;attribute name="ccbsPromotionId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="tariffId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="ccbsTariffId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="offerFromId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="processTypeFrom" type="{http://playmobile.pl/pc/types}ProcessType" />
 *       &lt;attribute name="ccbsPromotionFromId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="salesChannelFrom" type="{http://playmobile.pl/pc/types}SalesChannel" />
 *       &lt;attribute name="tariffFromId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="ccbsTariffFromId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="voucherId" type="{http://playmobile.pl/pc/types}VoucherIdOrAny" />
 *       &lt;attribute name="brand" type="{http://playmobile.pl/pc/types}BrandType" />
 *       &lt;attribute name="materialCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serviceType" type="{http://playmobile.pl/pc/types}ServiceType" />
 *       &lt;attribute name="noHandset" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="agreementType" type="{http://playmobile.pl/pc/types}AgreementType" />
 *       &lt;attribute name="offerDate" type="{http://playmobile.pl/pc/types}Date" />
 *       &lt;attribute name="clientLegalType" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="segmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subSegmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="productPriceListId" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="isTemporary" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="temporaryOfferId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="temporaryOfferDuration" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetOffersRequest")
public class GetOffersRequest
    extends BaseRequestWithRoles
{

    @XmlAttribute(name = "offerId")
    protected Long offerId;
    @XmlAttribute(name = "processType")
    protected ProcessType processType;
    @XmlAttribute(name = "ccbsPromotionId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long ccbsPromotionId;
    @XmlAttribute(name = "tariffId")
    protected String tariffId;
    @XmlAttribute(name = "ccbsTariffId")
    protected String ccbsTariffId;
    @XmlAttribute(name = "offerFromId")
    protected Long offerFromId;
    @XmlAttribute(name = "processTypeFrom")
    protected ProcessType processTypeFrom;
    @XmlAttribute(name = "ccbsPromotionFromId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long ccbsPromotionFromId;
    @XmlAttribute(name = "salesChannelFrom")
    protected SalesChannel salesChannelFrom;
    @XmlAttribute(name = "tariffFromId")
    protected String tariffFromId;
    @XmlAttribute(name = "ccbsTariffFromId")
    protected String ccbsTariffFromId;
    @XmlAttribute(name = "voucherId")
    protected String voucherId;
    @XmlAttribute(name = "brand")
    protected BrandType brand;
    @XmlAttribute(name = "materialCode")
    protected String materialCode;
    @XmlAttribute(name = "serviceType")
    protected ServiceType serviceType;
    @XmlAttribute(name = "noHandset")
    protected Boolean noHandset;
    @XmlAttribute(name = "agreementType")
    protected AgreementType agreementType;
    @XmlAttribute(name = "offerDate")
    protected XMLGregorianCalendar offerDate;
    @XmlAttribute(name = "clientLegalType")
    protected Long clientLegalType;
    @XmlAttribute(name = "segmentName")
    protected String segmentName;
    @XmlAttribute(name = "subSegmentName")
    protected String subSegmentName;
    @XmlAttribute(name = "productPriceListId")
    protected BigInteger productPriceListId;
    @XmlAttribute(name = "isTemporary")
    protected Boolean isTemporary;
    @XmlAttribute(name = "temporaryOfferId")
    protected Long temporaryOfferId;
    @XmlAttribute(name = "temporaryOfferDuration")
    protected BigInteger temporaryOfferDuration;

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferId(Long value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the processType property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessType }
     *     
     */
    public ProcessType getProcessType() {
        return processType;
    }

    /**
     * Sets the value of the processType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessType }
     *     
     */
    public void setProcessType(ProcessType value) {
        this.processType = value;
    }

    /**
     * Gets the value of the ccbsPromotionId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPromotionId() {
        return ccbsPromotionId;
    }

    /**
     * Sets the value of the ccbsPromotionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPromotionId(Long value) {
        this.ccbsPromotionId = value;
    }

    /**
     * Gets the value of the tariffId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffId() {
        return tariffId;
    }

    /**
     * Sets the value of the tariffId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffId(String value) {
        this.tariffId = value;
    }

    /**
     * Gets the value of the ccbsTariffId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffId() {
        return ccbsTariffId;
    }

    /**
     * Sets the value of the ccbsTariffId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffId(String value) {
        this.ccbsTariffId = value;
    }

    /**
     * Gets the value of the offerFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferFromId() {
        return offerFromId;
    }

    /**
     * Sets the value of the offerFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferFromId(Long value) {
        this.offerFromId = value;
    }

    /**
     * Gets the value of the processTypeFrom property.
     * 
     * @return
     *     possible object is
     *     {@link ProcessType }
     *     
     */
    public ProcessType getProcessTypeFrom() {
        return processTypeFrom;
    }

    /**
     * Sets the value of the processTypeFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProcessType }
     *     
     */
    public void setProcessTypeFrom(ProcessType value) {
        this.processTypeFrom = value;
    }

    /**
     * Gets the value of the ccbsPromotionFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPromotionFromId() {
        return ccbsPromotionFromId;
    }

    /**
     * Sets the value of the ccbsPromotionFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPromotionFromId(Long value) {
        this.ccbsPromotionFromId = value;
    }

    /**
     * Gets the value of the salesChannelFrom property.
     * 
     * @return
     *     possible object is
     *     {@link SalesChannel }
     *     
     */
    public SalesChannel getSalesChannelFrom() {
        return salesChannelFrom;
    }

    /**
     * Sets the value of the salesChannelFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesChannel }
     *     
     */
    public void setSalesChannelFrom(SalesChannel value) {
        this.salesChannelFrom = value;
    }

    /**
     * Gets the value of the tariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffFromId() {
        return tariffFromId;
    }

    /**
     * Sets the value of the tariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffFromId(String value) {
        this.tariffFromId = value;
    }

    /**
     * Gets the value of the ccbsTariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffFromId() {
        return ccbsTariffFromId;
    }

    /**
     * Sets the value of the ccbsTariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffFromId(String value) {
        this.ccbsTariffFromId = value;
    }

    /**
     * Gets the value of the voucherId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherId() {
        return voucherId;
    }

    /**
     * Sets the value of the voucherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherId(String value) {
        this.voucherId = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link BrandType }
     *     
     */
    public BrandType getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandType }
     *     
     */
    public void setBrand(BrandType value) {
        this.brand = value;
    }

    /**
     * Gets the value of the materialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * Sets the value of the materialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialCode(String value) {
        this.materialCode = value;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setServiceType(ServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the noHandset property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoHandset() {
        return noHandset;
    }

    /**
     * Sets the value of the noHandset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoHandset(Boolean value) {
        this.noHandset = value;
    }

    /**
     * Gets the value of the agreementType property.
     * 
     * @return
     *     possible object is
     *     {@link AgreementType }
     *     
     */
    public AgreementType getAgreementType() {
        return agreementType;
    }

    /**
     * Sets the value of the agreementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link AgreementType }
     *     
     */
    public void setAgreementType(AgreementType value) {
        this.agreementType = value;
    }

    /**
     * Gets the value of the offerDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOfferDate() {
        return offerDate;
    }

    /**
     * Sets the value of the offerDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOfferDate(XMLGregorianCalendar value) {
        this.offerDate = value;
    }

    /**
     * Gets the value of the clientLegalType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientLegalType() {
        return clientLegalType;
    }

    /**
     * Sets the value of the clientLegalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientLegalType(Long value) {
        this.clientLegalType = value;
    }

    /**
     * Gets the value of the segmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentName() {
        return segmentName;
    }

    /**
     * Sets the value of the segmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentName(String value) {
        this.segmentName = value;
    }

    /**
     * Gets the value of the subSegmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSegmentName() {
        return subSegmentName;
    }

    /**
     * Sets the value of the subSegmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSegmentName(String value) {
        this.subSegmentName = value;
    }

    /**
     * Gets the value of the productPriceListId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getProductPriceListId() {
        return productPriceListId;
    }

    /**
     * Sets the value of the productPriceListId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setProductPriceListId(BigInteger value) {
        this.productPriceListId = value;
    }

    /**
     * Gets the value of the isTemporary property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsTemporary() {
        return isTemporary;
    }

    /**
     * Sets the value of the isTemporary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsTemporary(Boolean value) {
        this.isTemporary = value;
    }

    /**
     * Gets the value of the temporaryOfferId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTemporaryOfferId() {
        return temporaryOfferId;
    }

    /**
     * Sets the value of the temporaryOfferId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTemporaryOfferId(Long value) {
        this.temporaryOfferId = value;
    }

    /**
     * Gets the value of the temporaryOfferDuration property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTemporaryOfferDuration() {
        return temporaryOfferDuration;
    }

    /**
     * Sets the value of the temporaryOfferDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTemporaryOfferDuration(BigInteger value) {
        this.temporaryOfferDuration = value;
    }

}
