//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * typ komunikatu s³u¿¹cy do pobrania oferty akwizycynej retencji
 * 
 * <p>Java class for GetRetentionOffers2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRetentionOffers2">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseRequestWithRoles">
 *       &lt;attribute name="msisdn" use="required" type="{http://playmobile.pl/pc/types}MSISDN" />
 *       &lt;attribute name="offerDate" type="{http://playmobile.pl/pc/types}Date" />
 *       &lt;attribute name="materialCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="offerId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="voucherId" type="{http://playmobile.pl/pc/types}VoucherId" />
 *       &lt;attribute name="tariffId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="ccbsTariffId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="ccbsPromotionId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="noHandset" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="ccbsTariffFromId" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="clientLegalType" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="segmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subSegmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="brand" type="{http://playmobile.pl/pc/types}BrandType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRetentionOffers2")
public class GetRetentionOffers2
    extends BaseRequestWithRoles
{

    @XmlAttribute(name = "msisdn", required = true)
    protected String msisdn;
    @XmlAttribute(name = "offerDate")
    protected XMLGregorianCalendar offerDate;
    @XmlAttribute(name = "materialCode")
    protected String materialCode;
    @XmlAttribute(name = "offerId")
    protected Long offerId;
    @XmlAttribute(name = "voucherId")
    protected String voucherId;
    @XmlAttribute(name = "tariffId")
    protected String tariffId;
    @XmlAttribute(name = "ccbsTariffId")
    protected String ccbsTariffId;
    @XmlAttribute(name = "ccbsPromotionId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long ccbsPromotionId;
    @XmlAttribute(name = "noHandset")
    protected Boolean noHandset;
    @XmlAttribute(name = "ccbsTariffFromId")
    protected String ccbsTariffFromId;
    @XmlAttribute(name = "clientLegalType")
    protected Long clientLegalType;
    @XmlAttribute(name = "segmentName")
    protected String segmentName;
    @XmlAttribute(name = "subSegmentName")
    protected String subSegmentName;
    @XmlAttribute(name = "brand")
    protected BrandType brand;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the offerDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOfferDate() {
        return offerDate;
    }

    /**
     * Sets the value of the offerDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOfferDate(XMLGregorianCalendar value) {
        this.offerDate = value;
    }

    /**
     * Gets the value of the materialCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialCode() {
        return materialCode;
    }

    /**
     * Sets the value of the materialCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialCode(String value) {
        this.materialCode = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferId(Long value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the voucherId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherId() {
        return voucherId;
    }

    /**
     * Sets the value of the voucherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherId(String value) {
        this.voucherId = value;
    }

    /**
     * Gets the value of the tariffId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffId() {
        return tariffId;
    }

    /**
     * Sets the value of the tariffId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffId(String value) {
        this.tariffId = value;
    }

    /**
     * Gets the value of the ccbsTariffId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffId() {
        return ccbsTariffId;
    }

    /**
     * Sets the value of the ccbsTariffId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffId(String value) {
        this.ccbsTariffId = value;
    }

    /**
     * Gets the value of the ccbsPromotionId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPromotionId() {
        return ccbsPromotionId;
    }

    /**
     * Sets the value of the ccbsPromotionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPromotionId(Long value) {
        this.ccbsPromotionId = value;
    }

    /**
     * Gets the value of the noHandset property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isNoHandset() {
        return noHandset;
    }

    /**
     * Sets the value of the noHandset property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setNoHandset(Boolean value) {
        this.noHandset = value;
    }

    /**
     * Gets the value of the ccbsTariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffFromId() {
        return ccbsTariffFromId;
    }

    /**
     * Sets the value of the ccbsTariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffFromId(String value) {
        this.ccbsTariffFromId = value;
    }

    /**
     * Gets the value of the clientLegalType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientLegalType() {
        return clientLegalType;
    }

    /**
     * Sets the value of the clientLegalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientLegalType(Long value) {
        this.clientLegalType = value;
    }

    /**
     * Gets the value of the segmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentName() {
        return segmentName;
    }

    /**
     * Sets the value of the segmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentName(String value) {
        this.segmentName = value;
    }

    /**
     * Gets the value of the subSegmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSegmentName() {
        return subSegmentName;
    }

    /**
     * Sets the value of the subSegmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSegmentName(String value) {
        this.subSegmentName = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link BrandType }
     *     
     */
    public BrandType getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandType }
     *     
     */
    public void setBrand(BrandType value) {
        this.brand = value;
    }

}
