//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu s³u¿¹cy do pobrania statusu i ofert w procesach migracyjnych
 * 
 * <p>Java class for GetRetentionStatusAndOffers2 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRetentionStatusAndOffers2">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseRequestWithRoles">
 *       &lt;attribute name="msisdn" use="required" type="{http://playmobile.pl/pc/types}MSISDN" />
 *       &lt;attribute name="voucherId" type="{http://playmobile.pl/pc/types}VoucherId" />
 *       &lt;attribute name="offerFromId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="ccbsPromotionFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="tariffFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="ccbsPackageFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="segmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="subSegmentName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRetentionStatusAndOffers2")
public class GetRetentionStatusAndOffers2
    extends BaseRequestWithRoles
{

    @XmlAttribute(name = "msisdn", required = true)
    protected String msisdn;
    @XmlAttribute(name = "voucherId")
    protected String voucherId;
    @XmlAttribute(name = "offerFromId")
    protected Long offerFromId;
    @XmlAttribute(name = "ccbsPromotionFromId")
    protected Long ccbsPromotionFromId;
    @XmlAttribute(name = "tariffFromId")
    protected Long tariffFromId;
    @XmlAttribute(name = "ccbsPackageFromId")
    protected Long ccbsPackageFromId;
    @XmlAttribute(name = "segmentName")
    protected String segmentName;
    @XmlAttribute(name = "subSegmentName")
    protected String subSegmentName;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the voucherId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVoucherId() {
        return voucherId;
    }

    /**
     * Sets the value of the voucherId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVoucherId(String value) {
        this.voucherId = value;
    }

    /**
     * Gets the value of the offerFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferFromId() {
        return offerFromId;
    }

    /**
     * Sets the value of the offerFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferFromId(Long value) {
        this.offerFromId = value;
    }

    /**
     * Gets the value of the ccbsPromotionFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPromotionFromId() {
        return ccbsPromotionFromId;
    }

    /**
     * Sets the value of the ccbsPromotionFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPromotionFromId(Long value) {
        this.ccbsPromotionFromId = value;
    }

    /**
     * Gets the value of the tariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getTariffFromId() {
        return tariffFromId;
    }

    /**
     * Sets the value of the tariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setTariffFromId(Long value) {
        this.tariffFromId = value;
    }

    /**
     * Gets the value of the ccbsPackageFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPackageFromId() {
        return ccbsPackageFromId;
    }

    /**
     * Sets the value of the ccbsPackageFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPackageFromId(Long value) {
        this.ccbsPackageFromId = value;
    }

    /**
     * Gets the value of the segmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSegmentName() {
        return segmentName;
    }

    /**
     * Sets the value of the segmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSegmentName(String value) {
        this.segmentName = value;
    }

    /**
     * Gets the value of the subSegmentName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubSegmentName() {
        return subSegmentName;
    }

    /**
     * Sets the value of the subSegmentName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubSegmentName(String value) {
        this.subSegmentName = value;
    }

}
