//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu odpowiedzi do pobrania status retencji
 * 
 * <p>Java class for GetRetentionStatusResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRetentionStatusResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="retentionStatus" type="{http://playmobile.pl/pc/types}RetentionOfferStatus" minOccurs="0"/>
 *         &lt;element name="segmentStatus" type="{http://playmobile.pl/pc/types}SegmentStatus" minOccurs="0"/>
 *         &lt;element name="bucket" type="{http://playmobile.pl/pc/types}PhoneBucket" minOccurs="0"/>
 *         &lt;element name="processTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="processType" type="{http://playmobile.pl/pc/types}ProcessType" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRetentionStatusResponse", propOrder = {
    "retentionStatus",
    "segmentStatus",
    "bucket",
    "processTypes"
})
public class GetRetentionStatusResponse {

    protected RetentionOfferStatus retentionStatus;
    protected SegmentStatus segmentStatus;
    protected PhoneBucket bucket;
    protected GetRetentionStatusResponse.ProcessTypes processTypes;

    /**
     * Gets the value of the retentionStatus property.
     * 
     * @return
     *     possible object is
     *     {@link RetentionOfferStatus }
     *     
     */
    public RetentionOfferStatus getRetentionStatus() {
        return retentionStatus;
    }

    /**
     * Sets the value of the retentionStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetentionOfferStatus }
     *     
     */
    public void setRetentionStatus(RetentionOfferStatus value) {
        this.retentionStatus = value;
    }

    /**
     * Gets the value of the segmentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link SegmentStatus }
     *     
     */
    public SegmentStatus getSegmentStatus() {
        return segmentStatus;
    }

    /**
     * Sets the value of the segmentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link SegmentStatus }
     *     
     */
    public void setSegmentStatus(SegmentStatus value) {
        this.segmentStatus = value;
    }

    /**
     * Gets the value of the bucket property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneBucket }
     *     
     */
    public PhoneBucket getBucket() {
        return bucket;
    }

    /**
     * Sets the value of the bucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneBucket }
     *     
     */
    public void setBucket(PhoneBucket value) {
        this.bucket = value;
    }

    /**
     * Gets the value of the processTypes property.
     * 
     * @return
     *     possible object is
     *     {@link GetRetentionStatusResponse.ProcessTypes }
     *     
     */
    public GetRetentionStatusResponse.ProcessTypes getProcessTypes() {
        return processTypes;
    }

    /**
     * Sets the value of the processTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetRetentionStatusResponse.ProcessTypes }
     *     
     */
    public void setProcessTypes(GetRetentionStatusResponse.ProcessTypes value) {
        this.processTypes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="processType" type="{http://playmobile.pl/pc/types}ProcessType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "processType"
    })
    public static class ProcessTypes {

        @XmlSchemaType(name = "string")
        protected List<ProcessType> processType;

        /**
         * Gets the value of the processType property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the processType property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcessType().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ProcessType }
         * 
         * 
         */
        public List<ProcessType> getProcessType() {
            if (processType == null) {
                processType = new ArrayList<ProcessType>();
            }
            return this.processType;
        }

    }

}
