//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu s³u¿¹cy do pobrania statusu retencji
 * 
 * <p>Java class for GetRetentionStatusAdapterVersion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetRetentionStatusAdapterVersion">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}GetRetentionStatus">
 *       &lt;sequence>
 *         &lt;element name="bucket" type="{http://playmobile.pl/pc/types}PhoneBucket" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="recommendedTariffId" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="recommendedTariffName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetRetentionStatusAdapterVersion", propOrder = {
    "bucket"
})
public class GetRetentionStatusAdapterVersion
    extends GetRetentionStatus
{

    protected PhoneBucket bucket;
    @XmlAttribute(name = "recommendedTariffId")
    protected String recommendedTariffId;
    @XmlAttribute(name = "recommendedTariffName")
    protected String recommendedTariffName;

    /**
     * Gets the value of the bucket property.
     * 
     * @return
     *     possible object is
     *     {@link PhoneBucket }
     *     
     */
    public PhoneBucket getBucket() {
        return bucket;
    }

    /**
     * Sets the value of the bucket property.
     * 
     * @param value
     *     allowed object is
     *     {@link PhoneBucket }
     *     
     */
    public void setBucket(PhoneBucket value) {
        this.bucket = value;
    }

    /**
     * Gets the value of the recommendedTariffId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendedTariffId() {
        return recommendedTariffId;
    }

    /**
     * Sets the value of the recommendedTariffId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendedTariffId(String value) {
        this.recommendedTariffId = value;
    }

    /**
     * Gets the value of the recommendedTariffName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecommendedTariffName() {
        return recommendedTariffName;
    }

    /**
     * Sets the value of the recommendedTariffName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecommendedTariffName(String value) {
        this.recommendedTariffName = value;
    }

}
