//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu s³u¿¹cy do pobrania informacje o wykorzystaniu kwotowym
 *             
 * 
 * <p>Java class for GetUsageInfoOperation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetUsageInfoOperation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseRequestWithRoles">
 *       &lt;attribute name="msisdn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="serviceInternalId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="serviceInternalIdResets" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUsageInfoOperation")
public class GetUsageInfoOperation
    extends BaseRequestWithRoles
{

    @XmlAttribute(name = "msisdn")
    protected String msisdn;
    @XmlAttribute(name = "serviceInternalId")
    protected Long serviceInternalId;
    @XmlAttribute(name = "serviceInternalIdResets")
    protected BigInteger serviceInternalIdResets;

    /**
     * Gets the value of the msisdn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMsisdn() {
        return msisdn;
    }

    /**
     * Sets the value of the msisdn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMsisdn(String value) {
        this.msisdn = value;
    }

    /**
     * Gets the value of the serviceInternalId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getServiceInternalId() {
        return serviceInternalId;
    }

    /**
     * Sets the value of the serviceInternalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setServiceInternalId(Long value) {
        this.serviceInternalId = value;
    }

    /**
     * Gets the value of the serviceInternalIdResets property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getServiceInternalIdResets() {
        return serviceInternalIdResets;
    }

    /**
     * Sets the value of the serviceInternalIdResets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setServiceInternalIdResets(BigInteger value) {
        this.serviceInternalIdResets = value;
    }

}
