//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu s³u¿¹cy jako odpowiedz do pobrania informacje o wykorzystaniu kwotowym
 *             
 * 
 * <p>Java class for GetUsageInfoOperationResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetUsageInfoOperationResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="onNetBalance" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="allNetBalance" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="smsBalance" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="invoice" type="{http://playmobile.pl/pc/types}Amount" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUsageInfoOperationResponse")
public class GetUsageInfoOperationResponse {

    @XmlAttribute(name = "onNetBalance")
    protected BigDecimal onNetBalance;
    @XmlAttribute(name = "allNetBalance")
    protected BigDecimal allNetBalance;
    @XmlAttribute(name = "smsBalance")
    protected BigDecimal smsBalance;
    @XmlAttribute(name = "invoice")
    protected BigDecimal invoice;

    /**
     * Gets the value of the onNetBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getOnNetBalance() {
        return onNetBalance;
    }

    /**
     * Sets the value of the onNetBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setOnNetBalance(BigDecimal value) {
        this.onNetBalance = value;
    }

    /**
     * Gets the value of the allNetBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAllNetBalance() {
        return allNetBalance;
    }

    /**
     * Sets the value of the allNetBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAllNetBalance(BigDecimal value) {
        this.allNetBalance = value;
    }

    /**
     * Gets the value of the smsBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getSmsBalance() {
        return smsBalance;
    }

    /**
     * Sets the value of the smsBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setSmsBalance(BigDecimal value) {
        this.smsBalance = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getInvoice() {
        return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setInvoice(BigDecimal value) {
        this.invoice = value;
    }

}
