//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ komunikatu s³u¿¹cy do pobrania us³ug podpiêtych do oferty
 * 
 * <p>Java class for GetUpsellOffers complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetUpsellOffers">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseRequestWithRoles">
 *       &lt;attribute name="offerFromId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="ccbsTariffFromId" use="required" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="clientLegalType" type="{http://playmobile.pl/pc/types}ClientLegalType" />
 *       &lt;attribute name="ccbsPromotionFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUpsellOffers")
public class GetUpsellOffers
    extends BaseRequestWithRoles
{

    @XmlAttribute(name = "offerFromId")
    protected Long offerFromId;
    @XmlAttribute(name = "ccbsTariffFromId", required = true)
    protected String ccbsTariffFromId;
    @XmlAttribute(name = "clientLegalType")
    protected Long clientLegalType;
    @XmlAttribute(name = "ccbsPromotionFromId")
    protected Long ccbsPromotionFromId;

    /**
     * Gets the value of the offerFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferFromId() {
        return offerFromId;
    }

    /**
     * Sets the value of the offerFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferFromId(Long value) {
        this.offerFromId = value;
    }

    /**
     * Gets the value of the ccbsTariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffFromId() {
        return ccbsTariffFromId;
    }

    /**
     * Sets the value of the ccbsTariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffFromId(String value) {
        this.ccbsTariffFromId = value;
    }

    /**
     * Gets the value of the clientLegalType property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getClientLegalType() {
        return clientLegalType;
    }

    /**
     * Sets the value of the clientLegalType property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setClientLegalType(Long value) {
        this.clientLegalType = value;
    }

    /**
     * Gets the value of the ccbsPromotionFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPromotionFromId() {
        return ccbsPromotionFromId;
    }

    /**
     * Sets the value of the ccbsPromotionFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPromotionFromId(Long value) {
        this.ccbsPromotionFromId = value;
    }

}
