//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Odpowiedü dla operacji getOfferDetails
 * 
 * <p>Java class for GetUpsellOffersResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GetUpsellOffersResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="offerFrom" type="{http://playmobile.pl/pc/types}OfferFrom" minOccurs="0"/>
 *         &lt;element ref="{http://playmobile.pl/pc/types}offer" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GetUpsellOffersResponse", propOrder = {
    "offerFrom",
    "offer"
})
public class GetUpsellOffersResponse {

    protected OfferFrom offerFrom;
    protected List<Offer> offer;

    /**
     * Gets the value of the offerFrom property.
     * 
     * @return
     *     possible object is
     *     {@link OfferFrom }
     *     
     */
    public OfferFrom getOfferFrom() {
        return offerFrom;
    }

    /**
     * Sets the value of the offerFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link OfferFrom }
     *     
     */
    public void setOfferFrom(OfferFrom value) {
        this.offerFrom = value;
    }

    /**
     * Gets the value of the offer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Offer }
     * 
     * 
     */
    public List<Offer> getOffer() {
        if (offer == null) {
            offer = new ArrayList<Offer>();
        }
        return this.offer;
    }

}
