//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * typ aparatu telefonicznego
 * 
 * <p>Java class for Handset complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Handset">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}BaseHandset">
 *       &lt;attribute name="netPrice" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="grossPrice" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="priceListId" type="{http://www.w3.org/2001/XMLSchema}long" />
 *       &lt;attribute name="materialSymbol" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="offerId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="isPhone" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="productType" type="{http://playmobile.pl/pc/types}ProductType" />
 *       &lt;attribute name="productState" type="{http://playmobile.pl/pc/types}ProductStateType" />
 *       &lt;attribute name="isAllPhones" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="firstNetPayment" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="firstGrossPayment" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="grossPriceMin" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="grossPriceMax" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="netPriceMin" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="netPriceMax" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="model" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Handset")
@XmlSeeAlso({
    HandsetForGetOfferProduct.class
})
public class Handset
    extends BaseHandset
{

    @XmlAttribute(name = "netPrice")
    protected BigDecimal netPrice;
    @XmlAttribute(name = "grossPrice")
    protected BigDecimal grossPrice;
    @XmlAttribute(name = "priceListId")
    protected Long priceListId;
    @XmlAttribute(name = "materialSymbol", required = true)
    protected String materialSymbol;
    @XmlAttribute(name = "url")
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "offerId")
    protected Long offerId;
    @XmlAttribute(name = "isPhone")
    protected Boolean isPhone;
    @XmlAttribute(name = "manufacturer")
    protected String manufacturer;
    @XmlAttribute(name = "productType")
    protected ProductType productType;
    @XmlAttribute(name = "productState")
    protected ProductStateType productState;
    @XmlAttribute(name = "isAllPhones")
    protected Boolean isAllPhones;
    @XmlAttribute(name = "firstNetPayment")
    protected BigDecimal firstNetPayment;
    @XmlAttribute(name = "firstGrossPayment")
    protected BigDecimal firstGrossPayment;
    @XmlAttribute(name = "grossPriceMin")
    protected BigDecimal grossPriceMin;
    @XmlAttribute(name = "grossPriceMax")
    protected BigDecimal grossPriceMax;
    @XmlAttribute(name = "netPriceMin")
    protected BigDecimal netPriceMin;
    @XmlAttribute(name = "netPriceMax")
    protected BigDecimal netPriceMax;
    @XmlAttribute(name = "model")
    protected String model;

    /**
     * Gets the value of the netPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPrice() {
        return netPrice;
    }

    /**
     * Sets the value of the netPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPrice(BigDecimal value) {
        this.netPrice = value;
    }

    /**
     * Gets the value of the grossPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossPrice() {
        return grossPrice;
    }

    /**
     * Sets the value of the grossPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossPrice(BigDecimal value) {
        this.grossPrice = value;
    }

    /**
     * Gets the value of the priceListId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPriceListId() {
        return priceListId;
    }

    /**
     * Sets the value of the priceListId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPriceListId(Long value) {
        this.priceListId = value;
    }

    /**
     * Gets the value of the materialSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialSymbol() {
        return materialSymbol;
    }

    /**
     * Sets the value of the materialSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialSymbol(String value) {
        this.materialSymbol = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the offerId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferId() {
        return offerId;
    }

    /**
     * Sets the value of the offerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferId(Long value) {
        this.offerId = value;
    }

    /**
     * Gets the value of the isPhone property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPhone() {
        return isPhone;
    }

    /**
     * Sets the value of the isPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPhone(Boolean value) {
        this.isPhone = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setProductType(ProductType value) {
        this.productType = value;
    }

    /**
     * Gets the value of the productState property.
     * 
     * @return
     *     possible object is
     *     {@link ProductStateType }
     *     
     */
    public ProductStateType getProductState() {
        return productState;
    }

    /**
     * Sets the value of the productState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductStateType }
     *     
     */
    public void setProductState(ProductStateType value) {
        this.productState = value;
    }

    /**
     * Gets the value of the isAllPhones property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAllPhones() {
        return isAllPhones;
    }

    /**
     * Sets the value of the isAllPhones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAllPhones(Boolean value) {
        this.isAllPhones = value;
    }

    /**
     * Gets the value of the firstNetPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstNetPayment() {
        return firstNetPayment;
    }

    /**
     * Sets the value of the firstNetPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstNetPayment(BigDecimal value) {
        this.firstNetPayment = value;
    }

    /**
     * Gets the value of the firstGrossPayment property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFirstGrossPayment() {
        return firstGrossPayment;
    }

    /**
     * Sets the value of the firstGrossPayment property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFirstGrossPayment(BigDecimal value) {
        this.firstGrossPayment = value;
    }

    /**
     * Gets the value of the grossPriceMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossPriceMin() {
        return grossPriceMin;
    }

    /**
     * Sets the value of the grossPriceMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossPriceMin(BigDecimal value) {
        this.grossPriceMin = value;
    }

    /**
     * Gets the value of the grossPriceMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossPriceMax() {
        return grossPriceMax;
    }

    /**
     * Sets the value of the grossPriceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossPriceMax(BigDecimal value) {
        this.grossPriceMax = value;
    }

    /**
     * Gets the value of the netPriceMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPriceMin() {
        return netPriceMin;
    }

    /**
     * Sets the value of the netPriceMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPriceMin(BigDecimal value) {
        this.netPriceMin = value;
    }

    /**
     * Gets the value of the netPriceMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPriceMax() {
        return netPriceMax;
    }

    /**
     * Sets the value of the netPriceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPriceMax(BigDecimal value) {
        this.netPriceMax = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

}
