//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * typ wyci¹gu aparatu telefonicznego
 * 
 * <p>Java class for HandsetInfo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HandsetInfo">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://playmobile.pl/pc/types}features" minOccurs="0"/>
 *         &lt;element ref="{http://playmobile.pl/pc/types}tac" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="isPhone" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="url" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="materialSymbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="grossPriceMin" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="grossPriceMax" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="netPriceMin" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="netPriceMax" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="description" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="phoneId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="manufacturer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isAllPhones" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="brand" type="{http://playmobile.pl/pc/types}BrandType" />
 *       &lt;attribute name="productType" type="{http://playmobile.pl/pc/types}ProductType" />
 *       &lt;attribute name="productState" type="{http://playmobile.pl/pc/types}ProductStateType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HandsetInfo", propOrder = {
    "features",
    "tac"
})
public class HandsetInfo {

    protected Features features;
    protected List<String> tac;
    @XmlAttribute(name = "isPhone")
    protected Boolean isPhone;
    @XmlAttribute(name = "url")
    @XmlSchemaType(name = "anyURI")
    protected String url;
    @XmlAttribute(name = "materialSymbol")
    protected String materialSymbol;
    @XmlAttribute(name = "grossPriceMin")
    protected BigDecimal grossPriceMin;
    @XmlAttribute(name = "grossPriceMax")
    protected BigDecimal grossPriceMax;
    @XmlAttribute(name = "netPriceMin")
    protected BigDecimal netPriceMin;
    @XmlAttribute(name = "netPriceMax")
    protected BigDecimal netPriceMax;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "description")
    protected String description;
    @XmlAttribute(name = "phoneId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long phoneId;
    @XmlAttribute(name = "manufacturer")
    protected String manufacturer;
    @XmlAttribute(name = "isAllPhones")
    protected Boolean isAllPhones;
    @XmlAttribute(name = "brand")
    protected BrandType brand;
    @XmlAttribute(name = "productType")
    protected ProductType productType;
    @XmlAttribute(name = "productState")
    protected ProductStateType productState;

    /**
     * Gets the value of the features property.
     * 
     * @return
     *     possible object is
     *     {@link Features }
     *     
     */
    public Features getFeatures() {
        return features;
    }

    /**
     * Sets the value of the features property.
     * 
     * @param value
     *     allowed object is
     *     {@link Features }
     *     
     */
    public void setFeatures(Features value) {
        this.features = value;
    }

    /**
     * Gets the value of the tac property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tac property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTac().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTac() {
        if (tac == null) {
            tac = new ArrayList<String>();
        }
        return this.tac;
    }

    /**
     * Gets the value of the isPhone property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPhone() {
        return isPhone;
    }

    /**
     * Sets the value of the isPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPhone(Boolean value) {
        this.isPhone = value;
    }

    /**
     * Gets the value of the url property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUrl() {
        return url;
    }

    /**
     * Sets the value of the url property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUrl(String value) {
        this.url = value;
    }

    /**
     * Gets the value of the materialSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaterialSymbol() {
        return materialSymbol;
    }

    /**
     * Sets the value of the materialSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaterialSymbol(String value) {
        this.materialSymbol = value;
    }

    /**
     * Gets the value of the grossPriceMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossPriceMin() {
        return grossPriceMin;
    }

    /**
     * Sets the value of the grossPriceMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossPriceMin(BigDecimal value) {
        this.grossPriceMin = value;
    }

    /**
     * Gets the value of the grossPriceMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGrossPriceMax() {
        return grossPriceMax;
    }

    /**
     * Sets the value of the grossPriceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGrossPriceMax(BigDecimal value) {
        this.grossPriceMax = value;
    }

    /**
     * Gets the value of the netPriceMin property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPriceMin() {
        return netPriceMin;
    }

    /**
     * Sets the value of the netPriceMin property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPriceMin(BigDecimal value) {
        this.netPriceMin = value;
    }

    /**
     * Gets the value of the netPriceMax property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getNetPriceMax() {
        return netPriceMax;
    }

    /**
     * Sets the value of the netPriceMax property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setNetPriceMax(BigDecimal value) {
        this.netPriceMax = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the phoneId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getPhoneId() {
        return phoneId;
    }

    /**
     * Sets the value of the phoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setPhoneId(Long value) {
        this.phoneId = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManufacturer() {
        return manufacturer;
    }

    /**
     * Sets the value of the manufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManufacturer(String value) {
        this.manufacturer = value;
    }

    /**
     * Gets the value of the isAllPhones property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsAllPhones() {
        return isAllPhones;
    }

    /**
     * Sets the value of the isAllPhones property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsAllPhones(Boolean value) {
        this.isAllPhones = value;
    }

    /**
     * Gets the value of the brand property.
     * 
     * @return
     *     possible object is
     *     {@link BrandType }
     *     
     */
    public BrandType getBrand() {
        return brand;
    }

    /**
     * Sets the value of the brand property.
     * 
     * @param value
     *     allowed object is
     *     {@link BrandType }
     *     
     */
    public void setBrand(BrandType value) {
        this.brand = value;
    }

    /**
     * Gets the value of the productType property.
     * 
     * @return
     *     possible object is
     *     {@link ProductType }
     *     
     */
    public ProductType getProductType() {
        return productType;
    }

    /**
     * Sets the value of the productType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductType }
     *     
     */
    public void setProductType(ProductType value) {
        this.productType = value;
    }

    /**
     * Gets the value of the productState property.
     * 
     * @return
     *     possible object is
     *     {@link ProductStateType }
     *     
     */
    public ProductStateType getProductState() {
        return productState;
    }

    /**
     * Sets the value of the productState property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductStateType }
     *     
     */
    public void setProductState(ProductStateType value) {
        this.productState = value;
    }

}
