//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rafal.kod.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SaveRetentionOffer2Response_QNAME = new QName("http://playmobile.pl/pc/types", "saveRetentionOffer2Response");
    private final static QName _GetMigrationTariffsPrepaidResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationTariffsPrepaidResponse");
    private final static QName _GetPhoneInfos_QNAME = new QName("http://playmobile.pl/pc/types", "getPhoneInfos");
    private final static QName _ProcessTypes_QNAME = new QName("http://playmobile.pl/pc/types", "processTypes");
    private final static QName _GetProductPenalty_QNAME = new QName("http://playmobile.pl/pc/types", "getProductPenalty");
    private final static QName _GetAllPhones_QNAME = new QName("http://playmobile.pl/pc/types", "getAllPhones");
    private final static QName _GetSavedRetention2_QNAME = new QName("http://playmobile.pl/pc/types", "getSavedRetention2");
    private final static QName _GetServicePointsResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getServicePointsResponse");
    private final static QName _GetAllOffers_QNAME = new QName("http://playmobile.pl/pc/types", "getAllOffers");
    private final static QName _UnlockRetentionOfferResponse_QNAME = new QName("http://playmobile.pl/pc/types", "unlockRetentionOfferResponse");
    private final static QName _GetVanityFeeResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getVanityFeeResponse");
    private final static QName _GetAdditionalFees_QNAME = new QName("http://playmobile.pl/pc/types", "getAdditionalFees");
    private final static QName _GetRetentionStatusAdapterVersion_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionStatusAdapterVersion");
    private final static QName _GetCfsInTariffsResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getCfsInTariffsResponse");
    private final static QName _GetMigrationTariffsPrepaid_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationTariffsPrepaid");
    private final static QName _GetMigrationOffers2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationOffers2Response");
    private final static QName _GetOfferServices2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getOfferServices2Response");
    private final static QName _GetMigrationTariffsResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationTariffsResponse");
    private final static QName _Product_QNAME = new QName("http://playmobile.pl/pc/types", "product");
    private final static QName _GetRetentionStatusAndOffers2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionStatusAndOffers2Response");
    private final static QName _SaveRetentionOffer2_QNAME = new QName("http://playmobile.pl/pc/types", "saveRetentionOffer2");
    private final static QName _Handset_QNAME = new QName("http://playmobile.pl/pc/types", "handset");
    private final static QName _GetVanityFee_QNAME = new QName("http://playmobile.pl/pc/types", "getVanityFee");
    private final static QName _Tariff_QNAME = new QName("http://playmobile.pl/pc/types", "tariff");
    private final static QName _GetProducts_QNAME = new QName("http://playmobile.pl/pc/types", "getProducts");
    private final static QName _GetOfferDetails2_QNAME = new QName("http://playmobile.pl/pc/types", "getOfferDetails2");
    private final static QName _GetSavedRetentionResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getSavedRetentionResponse");
    private final static QName _FaultInfo_QNAME = new QName("http://playmobile.pl/pc/types", "faultInfo");
    private final static QName _GetRetentionStatusAndOffers_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionStatusAndOffers");
    private final static QName _GetTariffServices2_QNAME = new QName("http://playmobile.pl/pc/types", "getTariffServices2");
    private final static QName _GetOffers2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getOffers2Response");
    private final static QName _Feature_QNAME = new QName("http://playmobile.pl/pc/types", "feature");
    private final static QName _GetProductServicingDetailsResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getProductServicingDetailsResponse");
    private final static QName _GetProductsResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getProductsResponse");
    private final static QName _GetCfsInTariffs_QNAME = new QName("http://playmobile.pl/pc/types", "getCfsInTariffs");
    private final static QName _GetAdditionalFeesResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getAdditionalFeesResponse");
    private final static QName _OfferPromotion_QNAME = new QName("http://playmobile.pl/pc/types", "offerPromotion");
    private final static QName _GetOffers_QNAME = new QName("http://playmobile.pl/pc/types", "getOffers");
    private final static QName _GetCfsResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getCfsResponse");
    private final static QName _OfferForGetAllOffers_QNAME = new QName("http://playmobile.pl/pc/types", "offerForGetAllOffers");
    private final static QName _GetTariffsResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getTariffsResponse");
    private final static QName _GetRetentionStatusResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionStatusResponse");
    private final static QName _GetUsageInfoResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getUsageInfoResponse");
    private final static QName _GetRetentionStatusAndOffers2_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionStatusAndOffers2");
    private final static QName _GetOffers2_QNAME = new QName("http://playmobile.pl/pc/types", "getOffers2");
    private final static QName _OfferId_QNAME = new QName("http://playmobile.pl/pc/types", "offerId");
    private final static QName _GetAllPhonesResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getAllPhonesResponse");
    private final static QName _GetRetentionStatusAndOffersResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionStatusAndOffersResponse");
    private final static QName _GetPhoneInfosResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getPhoneInfosResponse");
    private final static QName _GetPenaltyWithMaterialCode_QNAME = new QName("http://playmobile.pl/pc/types", "getPenaltyWithMaterialCode");
    private final static QName _GetUpsellOffers_QNAME = new QName("http://playmobile.pl/pc/types", "getUpsellOffers");
    private final static QName _UnlockRetentionOffer_QNAME = new QName("http://playmobile.pl/pc/types", "unlockRetentionOffer");
    private final static QName _LockRetentionOfferResponse_QNAME = new QName("http://playmobile.pl/pc/types", "lockRetentionOfferResponse");
    private final static QName _GetCfs_QNAME = new QName("http://playmobile.pl/pc/types", "getCfs");
    private final static QName _GetTariffServices2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getTariffServices2Response");
    private final static QName _GetMaxGroupMembersResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getMaxGroupMembersResponse");
    private final static QName _GetUsageInfo_QNAME = new QName("http://playmobile.pl/pc/types", "getUsageInfo");
    private final static QName _GetOfferProductResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getOfferProductResponse");
    private final static QName _CfsServices2_QNAME = new QName("http://playmobile.pl/pc/types", "cfsServices2");
    private final static QName _LockRetentionOffer_QNAME = new QName("http://playmobile.pl/pc/types", "lockRetentionOffer");
    private final static QName _GetMigrationProcessesWithOffers_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationProcessesWithOffers");
    private final static QName _GetMigrationOffers2_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationOffers2");
    private final static QName _GetMaxGroupMembers_QNAME = new QName("http://playmobile.pl/pc/types", "getMaxGroupMembers");
    private final static QName _GetPenaltyWithMaterialCodeResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getPenaltyWithMaterialCodeResponse");
    private final static QName _FaultInfoWithRequiredCfs_QNAME = new QName("http://playmobile.pl/pc/types", "faultInfoWithRequiredCfs");
    private final static QName _SaveRetentionOfferResponse_QNAME = new QName("http://playmobile.pl/pc/types", "saveRetentionOfferResponse");
    private final static QName _GetMigrationTariffs_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationTariffs");
    private final static QName _GetRetentionOffers2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionOffers2Response");
    private final static QName _GetProductServicingDetails_QNAME = new QName("http://playmobile.pl/pc/types", "getProductServicingDetails");
    private final static QName _GetAllOffersResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getAllOffersResponse");
    private final static QName _GetUpsellOffersResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getUpsellOffersResponse");
    private final static QName _SaveRetentionOffer_QNAME = new QName("http://playmobile.pl/pc/types", "saveRetentionOffer");
    private final static QName _GetOfferDetails2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getOfferDetails2Response");
    private final static QName _Features_QNAME = new QName("http://playmobile.pl/pc/types", "features");
    private final static QName _Offer_QNAME = new QName("http://playmobile.pl/pc/types", "offer");
    private final static QName _GetSavedRetention_QNAME = new QName("http://playmobile.pl/pc/types", "getSavedRetention");
    private final static QName _GetSavedRetention2Response_QNAME = new QName("http://playmobile.pl/pc/types", "getSavedRetention2Response");
    private final static QName _GetServicePoints_QNAME = new QName("http://playmobile.pl/pc/types", "getServicePoints");
    private final static QName _GetOffersResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getOffersResponse");
    private final static QName _GetRetentionStatus_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionStatus");
    private final static QName _Tac_QNAME = new QName("http://playmobile.pl/pc/types", "tac");
    private final static QName _GetProductPenaltyResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getProductPenaltyResponse");
    private final static QName _ServicePoints_QNAME = new QName("http://playmobile.pl/pc/types", "servicePoints");
    private final static QName _FinalPeriodFees_QNAME = new QName("http://playmobile.pl/pc/types", "finalPeriodFees");
    private final static QName _GetRetentionOffers2_QNAME = new QName("http://playmobile.pl/pc/types", "getRetentionOffers2");
    private final static QName _GetOfferProduct_QNAME = new QName("http://playmobile.pl/pc/types", "getOfferProduct");
    private final static QName _GetMigrationProcessesWithOffersResponse_QNAME = new QName("http://playmobile.pl/pc/types", "getMigrationProcessesWithOffersResponse");
    private final static QName _GetOfferServices2_QNAME = new QName("http://playmobile.pl/pc/types", "getOfferServices2");
    private final static QName _GetTariffs_QNAME = new QName("http://playmobile.pl/pc/types", "getTariffs");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rafal.kod.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SaveRetentionOffer2 }
     * 
     */
    public SaveRetentionOffer2 createSaveRetentionOffer2() {
        return new SaveRetentionOffer2();
    }

    /**
     * Create an instance of {@link GetSavedRetentionResponse }
     * 
     */
    public GetSavedRetentionResponse createGetSavedRetentionResponse() {
        return new GetSavedRetentionResponse();
    }

    /**
     * Create an instance of {@link GetRetentionStatusResponse }
     * 
     */
    public GetRetentionStatusResponse createGetRetentionStatusResponse() {
        return new GetRetentionStatusResponse();
    }

    /**
     * Create an instance of {@link SaveRetentionOffer }
     * 
     */
    public SaveRetentionOffer createSaveRetentionOffer() {
        return new SaveRetentionOffer();
    }

    /**
     * Create an instance of {@link GetSavedRetentionResponse2 }
     * 
     */
    public GetSavedRetentionResponse2 createGetSavedRetentionResponse2() {
        return new GetSavedRetentionResponse2();
    }

    /**
     * Create an instance of {@link GetMigrationProcessesWithOffersResponse }
     * 
     */
    public GetMigrationProcessesWithOffersResponse createGetMigrationProcessesWithOffersResponse() {
        return new GetMigrationProcessesWithOffersResponse();
    }

    /**
     * Create an instance of {@link GetOfferServices2 }
     * 
     */
    public GetOfferServices2 createGetOfferServices2() {
        return new GetOfferServices2();
    }

    /**
     * Create an instance of {@link GetTariffs }
     * 
     */
    public GetTariffs createGetTariffs() {
        return new GetTariffs();
    }

    /**
     * Create an instance of {@link ServicePoints }
     * 
     */
    public ServicePoints createServicePoints() {
        return new ServicePoints();
    }

    /**
     * Create an instance of {@link GetProductPenaltyResponse }
     * 
     */
    public GetProductPenaltyResponse createGetProductPenaltyResponse() {
        return new GetProductPenaltyResponse();
    }

    /**
     * Create an instance of {@link GetRetentionOffers2 }
     * 
     */
    public GetRetentionOffers2 createGetRetentionOffers2() {
        return new GetRetentionOffers2();
    }

    /**
     * Create an instance of {@link FinalPeriodFees }
     * 
     */
    public FinalPeriodFees createFinalPeriodFees() {
        return new FinalPeriodFees();
    }

    /**
     * Create an instance of {@link GetOfferProduct }
     * 
     */
    public GetOfferProduct createGetOfferProduct() {
        return new GetOfferProduct();
    }

    /**
     * Create an instance of {@link Offer }
     * 
     */
    public Offer createOffer() {
        return new Offer();
    }

    /**
     * Create an instance of {@link Features }
     * 
     */
    public Features createFeatures() {
        return new Features();
    }

    /**
     * Create an instance of {@link GetServicePoints }
     * 
     */
    public GetServicePoints createGetServicePoints() {
        return new GetServicePoints();
    }

    /**
     * Create an instance of {@link GetOffersResponse }
     * 
     */
    public GetOffersResponse createGetOffersResponse() {
        return new GetOffersResponse();
    }

    /**
     * Create an instance of {@link GetSavedRetention }
     * 
     */
    public GetSavedRetention createGetSavedRetention() {
        return new GetSavedRetention();
    }

    /**
     * Create an instance of {@link GetRetentionStatus }
     * 
     */
    public GetRetentionStatus createGetRetentionStatus() {
        return new GetRetentionStatus();
    }

    /**
     * Create an instance of {@link GetMigrationTariffs }
     * 
     */
    public GetMigrationTariffs createGetMigrationTariffs() {
        return new GetMigrationTariffs();
    }

    /**
     * Create an instance of {@link GetOffers2Response }
     * 
     */
    public GetOffers2Response createGetOffers2Response() {
        return new GetOffers2Response();
    }

    /**
     * Create an instance of {@link GetProductServicingDetails }
     * 
     */
    public GetProductServicingDetails createGetProductServicingDetails() {
        return new GetProductServicingDetails();
    }

    /**
     * Create an instance of {@link GetUpsellOffersResponse }
     * 
     */
    public GetUpsellOffersResponse createGetUpsellOffersResponse() {
        return new GetUpsellOffersResponse();
    }

    /**
     * Create an instance of {@link GetAllOffersResponse }
     * 
     */
    public GetAllOffersResponse createGetAllOffersResponse() {
        return new GetAllOffersResponse();
    }

    /**
     * Create an instance of {@link GetOfferDetailsResponse2 }
     * 
     */
    public GetOfferDetailsResponse2 createGetOfferDetailsResponse2() {
        return new GetOfferDetailsResponse2();
    }

    /**
     * Create an instance of {@link GetMaxGroupMembers }
     * 
     */
    public GetMaxGroupMembers createGetMaxGroupMembers() {
        return new GetMaxGroupMembers();
    }

    /**
     * Create an instance of {@link GetPenaltyWithMaterialCodeOperationResponse }
     * 
     */
    public GetPenaltyWithMaterialCodeOperationResponse createGetPenaltyWithMaterialCodeOperationResponse() {
        return new GetPenaltyWithMaterialCodeOperationResponse();
    }

    /**
     * Create an instance of {@link FaultInfoWithRequiredCfs }
     * 
     */
    public FaultInfoWithRequiredCfs createFaultInfoWithRequiredCfs() {
        return new FaultInfoWithRequiredCfs();
    }

    /**
     * Create an instance of {@link CFSServices2 }
     * 
     */
    public CFSServices2 createCFSServices2() {
        return new CFSServices2();
    }

    /**
     * Create an instance of {@link GetMigrationProcessesWithOffers }
     * 
     */
    public GetMigrationProcessesWithOffers createGetMigrationProcessesWithOffers() {
        return new GetMigrationProcessesWithOffers();
    }

    /**
     * Create an instance of {@link RetentionOfferOperation }
     * 
     */
    public RetentionOfferOperation createRetentionOfferOperation() {
        return new RetentionOfferOperation();
    }

    /**
     * Create an instance of {@link GetMigrationOffers2 }
     * 
     */
    public GetMigrationOffers2 createGetMigrationOffers2() {
        return new GetMigrationOffers2();
    }

    /**
     * Create an instance of {@link GetPenaltyWithMaterialCodeOperation }
     * 
     */
    public GetPenaltyWithMaterialCodeOperation createGetPenaltyWithMaterialCodeOperation() {
        return new GetPenaltyWithMaterialCodeOperation();
    }

    /**
     * Create an instance of {@link GetUpsellOffers }
     * 
     */
    public GetUpsellOffers createGetUpsellOffers() {
        return new GetUpsellOffers();
    }

    /**
     * Create an instance of {@link GetCfs }
     * 
     */
    public GetCfs createGetCfs() {
        return new GetCfs();
    }

    /**
     * Create an instance of {@link GetUsageInfoOperation }
     * 
     */
    public GetUsageInfoOperation createGetUsageInfoOperation() {
        return new GetUsageInfoOperation();
    }

    /**
     * Create an instance of {@link GetServicesResponse2 }
     * 
     */
    public GetServicesResponse2 createGetServicesResponse2() {
        return new GetServicesResponse2();
    }

    /**
     * Create an instance of {@link GetMaxGroupMembersResponse }
     * 
     */
    public GetMaxGroupMembersResponse createGetMaxGroupMembersResponse() {
        return new GetMaxGroupMembersResponse();
    }

    /**
     * Create an instance of {@link GetOfferProductResponse }
     * 
     */
    public GetOfferProductResponse createGetOfferProductResponse() {
        return new GetOfferProductResponse();
    }

    /**
     * Create an instance of {@link GetRetentionStatusAndOffers2 }
     * 
     */
    public GetRetentionStatusAndOffers2 createGetRetentionStatusAndOffers2() {
        return new GetRetentionStatusAndOffers2();
    }

    /**
     * Create an instance of {@link GetOffers }
     * 
     */
    public GetOffers createGetOffers() {
        return new GetOffers();
    }

    /**
     * Create an instance of {@link GetOfferPhonesResponse }
     * 
     */
    public GetOfferPhonesResponse createGetOfferPhonesResponse() {
        return new GetOfferPhonesResponse();
    }

    /**
     * Create an instance of {@link GetRetentionStatusAndOffersResponse }
     * 
     */
    public GetRetentionStatusAndOffersResponse createGetRetentionStatusAndOffersResponse() {
        return new GetRetentionStatusAndOffersResponse();
    }

    /**
     * Create an instance of {@link GetPhoneInfosResponse }
     * 
     */
    public GetPhoneInfosResponse createGetPhoneInfosResponse() {
        return new GetPhoneInfosResponse();
    }

    /**
     * Create an instance of {@link GetCfsInTariffs }
     * 
     */
    public GetCfsInTariffs createGetCfsInTariffs() {
        return new GetCfsInTariffs();
    }

    /**
     * Create an instance of {@link GetCfsResponse }
     * 
     */
    public GetCfsResponse createGetCfsResponse() {
        return new GetCfsResponse();
    }

    /**
     * Create an instance of {@link OfferForGetAllOffers }
     * 
     */
    public OfferForGetAllOffers createOfferForGetAllOffers() {
        return new OfferForGetAllOffers();
    }

    /**
     * Create an instance of {@link GetAdditionalFeesResponse }
     * 
     */
    public GetAdditionalFeesResponse createGetAdditionalFeesResponse() {
        return new GetAdditionalFeesResponse();
    }

    /**
     * Create an instance of {@link OfferPromotion }
     * 
     */
    public OfferPromotion createOfferPromotion() {
        return new OfferPromotion();
    }

    /**
     * Create an instance of {@link GetOffersRequest }
     * 
     */
    public GetOffersRequest createGetOffersRequest() {
        return new GetOffersRequest();
    }

    /**
     * Create an instance of {@link GetTariffsResponse }
     * 
     */
    public GetTariffsResponse createGetTariffsResponse() {
        return new GetTariffsResponse();
    }

    /**
     * Create an instance of {@link GetUsageInfoOperationResponse }
     * 
     */
    public GetUsageInfoOperationResponse createGetUsageInfoOperationResponse() {
        return new GetUsageInfoOperationResponse();
    }

    /**
     * Create an instance of {@link GetProductServicingDetailsResponse }
     * 
     */
    public GetProductServicingDetailsResponse createGetProductServicingDetailsResponse() {
        return new GetProductServicingDetailsResponse();
    }

    /**
     * Create an instance of {@link GetProductsResponse }
     * 
     */
    public GetProductsResponse createGetProductsResponse() {
        return new GetProductsResponse();
    }

    /**
     * Create an instance of {@link FaultInfo }
     * 
     */
    public FaultInfo createFaultInfo() {
        return new FaultInfo();
    }

    /**
     * Create an instance of {@link GetTariffServices2 }
     * 
     */
    public GetTariffServices2 createGetTariffServices2() {
        return new GetTariffServices2();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link GetRetentionStatusAndOffers }
     * 
     */
    public GetRetentionStatusAndOffers createGetRetentionStatusAndOffers() {
        return new GetRetentionStatusAndOffers();
    }

    /**
     * Create an instance of {@link Handset }
     * 
     */
    public Handset createHandset() {
        return new Handset();
    }

    /**
     * Create an instance of {@link GetVanityFee }
     * 
     */
    public GetVanityFee createGetVanityFee() {
        return new GetVanityFee();
    }

    /**
     * Create an instance of {@link Tariff }
     * 
     */
    public Tariff createTariff() {
        return new Tariff();
    }

    /**
     * Create an instance of {@link GetProducts }
     * 
     */
    public GetProducts createGetProducts() {
        return new GetProducts();
    }

    /**
     * Create an instance of {@link GetOfferDetailsRequest2 }
     * 
     */
    public GetOfferDetailsRequest2 createGetOfferDetailsRequest2() {
        return new GetOfferDetailsRequest2();
    }

    /**
     * Create an instance of {@link GetMigrationTariffsResponse }
     * 
     */
    public GetMigrationTariffsResponse createGetMigrationTariffsResponse() {
        return new GetMigrationTariffsResponse();
    }

    /**
     * Create an instance of {@link ProductInfo }
     * 
     */
    public ProductInfo createProductInfo() {
        return new ProductInfo();
    }

    /**
     * Create an instance of {@link GetRetentionStatusAndOffersResponse2 }
     * 
     */
    public GetRetentionStatusAndOffersResponse2 createGetRetentionStatusAndOffersResponse2() {
        return new GetRetentionStatusAndOffersResponse2();
    }

    /**
     * Create an instance of {@link GetVanityFeeResponse }
     * 
     */
    public GetVanityFeeResponse createGetVanityFeeResponse() {
        return new GetVanityFeeResponse();
    }

    /**
     * Create an instance of {@link GetAdditionalFees }
     * 
     */
    public GetAdditionalFees createGetAdditionalFees() {
        return new GetAdditionalFees();
    }

    /**
     * Create an instance of {@link GetMigrationTariffsPrepaid }
     * 
     */
    public GetMigrationTariffsPrepaid createGetMigrationTariffsPrepaid() {
        return new GetMigrationTariffsPrepaid();
    }

    /**
     * Create an instance of {@link GetRetentionStatusAdapterVersion }
     * 
     */
    public GetRetentionStatusAdapterVersion createGetRetentionStatusAdapterVersion() {
        return new GetRetentionStatusAdapterVersion();
    }

    /**
     * Create an instance of {@link GetCfsInTariffsResponse }
     * 
     */
    public GetCfsInTariffsResponse createGetCfsInTariffsResponse() {
        return new GetCfsInTariffsResponse();
    }

    /**
     * Create an instance of {@link GetServicePointsResponse }
     * 
     */
    public GetServicePointsResponse createGetServicePointsResponse() {
        return new GetServicePointsResponse();
    }

    /**
     * Create an instance of {@link GetAllOffersRequest }
     * 
     */
    public GetAllOffersRequest createGetAllOffersRequest() {
        return new GetAllOffersRequest();
    }

    /**
     * Create an instance of {@link GetMigrationTariffsPrepaidResponse }
     * 
     */
    public GetMigrationTariffsPrepaidResponse createGetMigrationTariffsPrepaidResponse() {
        return new GetMigrationTariffsPrepaidResponse();
    }

    /**
     * Create an instance of {@link GetAllPhones }
     * 
     */
    public GetAllPhones createGetAllPhones() {
        return new GetAllPhones();
    }

    /**
     * Create an instance of {@link GetSavedRetention2 }
     * 
     */
    public GetSavedRetention2 createGetSavedRetention2() {
        return new GetSavedRetention2();
    }

    /**
     * Create an instance of {@link GetPhoneInfos }
     * 
     */
    public GetPhoneInfos createGetPhoneInfos() {
        return new GetPhoneInfos();
    }

    /**
     * Create an instance of {@link rafal.kod.jaxb.ProcessTypes }
     * 
     */
    public rafal.kod.jaxb.ProcessTypes createProcessTypes() {
        return new rafal.kod.jaxb.ProcessTypes();
    }

    /**
     * Create an instance of {@link GetProductPenalty }
     * 
     */
    public GetProductPenalty createGetProductPenalty() {
        return new GetProductPenalty();
    }

    /**
     * Create an instance of {@link HandsetInfo }
     * 
     */
    public HandsetInfo createHandsetInfo() {
        return new HandsetInfo();
    }

    /**
     * Create an instance of {@link BaseGetOffers }
     * 
     */
    public BaseGetOffers createBaseGetOffers() {
        return new BaseGetOffers();
    }

    /**
     * Create an instance of {@link RelaxedOffer }
     * 
     */
    public RelaxedOffer createRelaxedOffer() {
        return new RelaxedOffer();
    }

    /**
     * Create an instance of {@link PhoneBucket }
     * 
     */
    public PhoneBucket createPhoneBucket() {
        return new PhoneBucket();
    }

    /**
     * Create an instance of {@link ProcessTypeWithOffers }
     * 
     */
    public ProcessTypeWithOffers createProcessTypeWithOffers() {
        return new ProcessTypeWithOffers();
    }

    /**
     * Create an instance of {@link RFSComponentAttributes }
     * 
     */
    public RFSComponentAttributes createRFSComponentAttributes() {
        return new RFSComponentAttributes();
    }

    /**
     * Create an instance of {@link GetOfferProductOrAllPhones }
     * 
     */
    public GetOfferProductOrAllPhones createGetOfferProductOrAllPhones() {
        return new GetOfferProductOrAllPhones();
    }

    /**
     * Create an instance of {@link OfferForGetOffers }
     * 
     */
    public OfferForGetOffers createOfferForGetOffers() {
        return new OfferForGetOffers();
    }

    /**
     * Create an instance of {@link VanityType }
     * 
     */
    public VanityType createVanityType() {
        return new VanityType();
    }

    /**
     * Create an instance of {@link Roles }
     * 
     */
    public Roles createRoles() {
        return new Roles();
    }

    /**
     * Create an instance of {@link BusinessCondition }
     * 
     */
    public BusinessCondition createBusinessCondition() {
        return new BusinessCondition();
    }

    /**
     * Create an instance of {@link DocumentLocation }
     * 
     */
    public DocumentLocation createDocumentLocation() {
        return new DocumentLocation();
    }

    /**
     * Create an instance of {@link CcbsPackageAndComponents }
     * 
     */
    public CcbsPackageAndComponents createCcbsPackageAndComponents() {
        return new CcbsPackageAndComponents();
    }

    /**
     * Create an instance of {@link RequiredCfs }
     * 
     */
    public RequiredCfs createRequiredCfs() {
        return new RequiredCfs();
    }

    /**
     * Create an instance of {@link RFSDiscountAttributes }
     * 
     */
    public RFSDiscountAttributes createRFSDiscountAttributes() {
        return new RFSDiscountAttributes();
    }

    /**
     * Create an instance of {@link RFSOtherAttributes }
     * 
     */
    public RFSOtherAttributes createRFSOtherAttributes() {
        return new RFSOtherAttributes();
    }

    /**
     * Create an instance of {@link DisplayParam }
     * 
     */
    public DisplayParam createDisplayParam() {
        return new DisplayParam();
    }

    /**
     * Create an instance of {@link MigrationTariff }
     * 
     */
    public MigrationTariff createMigrationTariff() {
        return new MigrationTariff();
    }

    /**
     * Create an instance of {@link OfferFrom }
     * 
     */
    public OfferFrom createOfferFrom() {
        return new OfferFrom();
    }

    /**
     * Create an instance of {@link Symptom }
     * 
     */
    public Symptom createSymptom() {
        return new Symptom();
    }

    /**
     * Create an instance of {@link DetailedOffer2 }
     * 
     */
    public DetailedOffer2 createDetailedOffer2() {
        return new DetailedOffer2();
    }

    /**
     * Create an instance of {@link DocumentLocations }
     * 
     */
    public DocumentLocations createDocumentLocations() {
        return new DocumentLocations();
    }

    /**
     * Create an instance of {@link CcbsParametersWithCfses }
     * 
     */
    public CcbsParametersWithCfses createCcbsParametersWithCfses() {
        return new CcbsParametersWithCfses();
    }

    /**
     * Create an instance of {@link RFSPIGAttributes }
     * 
     */
    public RFSPIGAttributes createRFSPIGAttributes() {
        return new RFSPIGAttributes();
    }

    /**
     * Create an instance of {@link OfferForGetSavedRetention }
     * 
     */
    public OfferForGetSavedRetention createOfferForGetSavedRetention() {
        return new OfferForGetSavedRetention();
    }

    /**
     * Create an instance of {@link ServicePoint }
     * 
     */
    public ServicePoint createServicePoint() {
        return new ServicePoint();
    }

    /**
     * Create an instance of {@link OfferIdWithLimit }
     * 
     */
    public OfferIdWithLimit createOfferIdWithLimit() {
        return new OfferIdWithLimit();
    }

    /**
     * Create an instance of {@link RFSVirtualAttributes }
     * 
     */
    public RFSVirtualAttributes createRFSVirtualAttributes() {
        return new RFSVirtualAttributes();
    }

    /**
     * Create an instance of {@link RetentionOfferStatus }
     * 
     */
    public RetentionOfferStatus createRetentionOfferStatus() {
        return new RetentionOfferStatus();
    }

    /**
     * Create an instance of {@link RFS }
     * 
     */
    public RFS createRFS() {
        return new RFS();
    }

    /**
     * Create an instance of {@link VanityPrefixType }
     * 
     */
    public VanityPrefixType createVanityPrefixType() {
        return new VanityPrefixType();
    }

    /**
     * Create an instance of {@link RfsParameterValue }
     * 
     */
    public RfsParameterValue createRfsParameterValue() {
        return new RfsParameterValue();
    }

    /**
     * Create an instance of {@link VirtualComponent }
     * 
     */
    public VirtualComponent createVirtualComponent() {
        return new VirtualComponent();
    }

    /**
     * Create an instance of {@link RfsId }
     * 
     */
    public RfsId createRfsId() {
        return new RfsId();
    }

    /**
     * Create an instance of {@link RelatedOfferIdsType }
     * 
     */
    public RelatedOfferIdsType createRelatedOfferIdsType() {
        return new RelatedOfferIdsType();
    }

    /**
     * Create an instance of {@link FeeElement }
     * 
     */
    public FeeElement createFeeElement() {
        return new FeeElement();
    }

    /**
     * Create an instance of {@link Price }
     * 
     */
    public Price createPrice() {
        return new Price();
    }

    /**
     * Create an instance of {@link RecommendedPhone }
     * 
     */
    public RecommendedPhone createRecommendedPhone() {
        return new RecommendedPhone();
    }

    /**
     * Create an instance of {@link BasePenalty }
     * 
     */
    public BasePenalty createBasePenalty() {
        return new BasePenalty();
    }

    /**
     * Create an instance of {@link Symptoms }
     * 
     */
    public Symptoms createSymptoms() {
        return new Symptoms();
    }

    /**
     * Create an instance of {@link BaseVoucher }
     * 
     */
    public BaseVoucher createBaseVoucher() {
        return new BaseVoucher();
    }

    /**
     * Create an instance of {@link SegmentStatus }
     * 
     */
    public SegmentStatus createSegmentStatus() {
        return new SegmentStatus();
    }

    /**
     * Create an instance of {@link HandsetForGetOfferProduct }
     * 
     */
    public HandsetForGetOfferProduct createHandsetForGetOfferProduct() {
        return new HandsetForGetOfferProduct();
    }

    /**
     * Create an instance of {@link FinalPeriodFee }
     * 
     */
    public FinalPeriodFee createFinalPeriodFee() {
        return new FinalPeriodFee();
    }

    /**
     * Create an instance of {@link RFSComponentParameters }
     * 
     */
    public RFSComponentParameters createRFSComponentParameters() {
        return new RFSComponentParameters();
    }

    /**
     * Create an instance of {@link CFS2 }
     * 
     */
    public CFS2 createCFS2() {
        return new CFS2();
    }

    /**
     * Create an instance of {@link SaveRetentionOffer2 .CfsIds }
     * 
     */
    public SaveRetentionOffer2 .CfsIds createSaveRetentionOffer2CfsIds() {
        return new SaveRetentionOffer2 .CfsIds();
    }

    /**
     * Create an instance of {@link GetSavedRetentionResponse.CfsIds }
     * 
     */
    public GetSavedRetentionResponse.CfsIds createGetSavedRetentionResponseCfsIds() {
        return new GetSavedRetentionResponse.CfsIds();
    }

    /**
     * Create an instance of {@link GetSavedRetentionResponse.RfsParameterValues }
     * 
     */
    public GetSavedRetentionResponse.RfsParameterValues createGetSavedRetentionResponseRfsParameterValues() {
        return new GetSavedRetentionResponse.RfsParameterValues();
    }

    /**
     * Create an instance of {@link GetRetentionStatusResponse.ProcessTypes }
     * 
     */
    public GetRetentionStatusResponse.ProcessTypes createGetRetentionStatusResponseProcessTypes() {
        return new GetRetentionStatusResponse.ProcessTypes();
    }

    /**
     * Create an instance of {@link SaveRetentionOffer.CfsIds }
     * 
     */
    public SaveRetentionOffer.CfsIds createSaveRetentionOfferCfsIds() {
        return new SaveRetentionOffer.CfsIds();
    }

    /**
     * Create an instance of {@link SaveRetentionOffer.RfsParameterValues }
     * 
     */
    public SaveRetentionOffer.RfsParameterValues createSaveRetentionOfferRfsParameterValues() {
        return new SaveRetentionOffer.RfsParameterValues();
    }

    /**
     * Create an instance of {@link GetSavedRetentionResponse2 .CfsIds }
     * 
     */
    public GetSavedRetentionResponse2 .CfsIds createGetSavedRetentionResponse2CfsIds() {
        return new GetSavedRetentionResponse2 .CfsIds();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferOperationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "saveRetentionOffer2Response")
    public JAXBElement<OfferOperationResponse> createSaveRetentionOffer2Response(OfferOperationResponse value) {
        return new JAXBElement<OfferOperationResponse>(_SaveRetentionOffer2Response_QNAME, OfferOperationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMigrationTariffsPrepaidResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationTariffsPrepaidResponse")
    public JAXBElement<GetMigrationTariffsPrepaidResponse> createGetMigrationTariffsPrepaidResponse(GetMigrationTariffsPrepaidResponse value) {
        return new JAXBElement<GetMigrationTariffsPrepaidResponse>(_GetMigrationTariffsPrepaidResponse_QNAME, GetMigrationTariffsPrepaidResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPhoneInfos }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getPhoneInfos")
    public JAXBElement<GetPhoneInfos> createGetPhoneInfos(GetPhoneInfos value) {
        return new JAXBElement<GetPhoneInfos>(_GetPhoneInfos_QNAME, GetPhoneInfos.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link rafal.kod.jaxb.ProcessTypes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "processTypes")
    public JAXBElement<rafal.kod.jaxb.ProcessTypes> createProcessTypes(rafal.kod.jaxb.ProcessTypes value) {
        return new JAXBElement<rafal.kod.jaxb.ProcessTypes>(_ProcessTypes_QNAME, rafal.kod.jaxb.ProcessTypes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductPenalty }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getProductPenalty")
    public JAXBElement<GetProductPenalty> createGetProductPenalty(GetProductPenalty value) {
        return new JAXBElement<GetProductPenalty>(_GetProductPenalty_QNAME, GetProductPenalty.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllPhones }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getAllPhones")
    public JAXBElement<GetAllPhones> createGetAllPhones(GetAllPhones value) {
        return new JAXBElement<GetAllPhones>(_GetAllPhones_QNAME, GetAllPhones.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSavedRetention2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getSavedRetention2")
    public JAXBElement<GetSavedRetention2> createGetSavedRetention2(GetSavedRetention2 value) {
        return new JAXBElement<GetSavedRetention2>(_GetSavedRetention2_QNAME, GetSavedRetention2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServicePointsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getServicePointsResponse")
    public JAXBElement<GetServicePointsResponse> createGetServicePointsResponse(GetServicePointsResponse value) {
        return new JAXBElement<GetServicePointsResponse>(_GetServicePointsResponse_QNAME, GetServicePointsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllOffersRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getAllOffers")
    public JAXBElement<GetAllOffersRequest> createGetAllOffers(GetAllOffersRequest value) {
        return new JAXBElement<GetAllOffersRequest>(_GetAllOffers_QNAME, GetAllOffersRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferOperationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "unlockRetentionOfferResponse")
    public JAXBElement<OfferOperationResponse> createUnlockRetentionOfferResponse(OfferOperationResponse value) {
        return new JAXBElement<OfferOperationResponse>(_UnlockRetentionOfferResponse_QNAME, OfferOperationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetVanityFeeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getVanityFeeResponse")
    public JAXBElement<GetVanityFeeResponse> createGetVanityFeeResponse(GetVanityFeeResponse value) {
        return new JAXBElement<GetVanityFeeResponse>(_GetVanityFeeResponse_QNAME, GetVanityFeeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAdditionalFees }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getAdditionalFees")
    public JAXBElement<GetAdditionalFees> createGetAdditionalFees(GetAdditionalFees value) {
        return new JAXBElement<GetAdditionalFees>(_GetAdditionalFees_QNAME, GetAdditionalFees.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionStatusAdapterVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionStatusAdapterVersion")
    public JAXBElement<GetRetentionStatusAdapterVersion> createGetRetentionStatusAdapterVersion(GetRetentionStatusAdapterVersion value) {
        return new JAXBElement<GetRetentionStatusAdapterVersion>(_GetRetentionStatusAdapterVersion_QNAME, GetRetentionStatusAdapterVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCfsInTariffsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getCfsInTariffsResponse")
    public JAXBElement<GetCfsInTariffsResponse> createGetCfsInTariffsResponse(GetCfsInTariffsResponse value) {
        return new JAXBElement<GetCfsInTariffsResponse>(_GetCfsInTariffsResponse_QNAME, GetCfsInTariffsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMigrationTariffsPrepaid }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationTariffsPrepaid")
    public JAXBElement<GetMigrationTariffsPrepaid> createGetMigrationTariffsPrepaid(GetMigrationTariffsPrepaid value) {
        return new JAXBElement<GetMigrationTariffsPrepaid>(_GetMigrationTariffsPrepaid_QNAME, GetMigrationTariffsPrepaid.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOffers2Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationOffers2Response")
    public JAXBElement<GetOffers2Response> createGetMigrationOffers2Response(GetOffers2Response value) {
        return new JAXBElement<GetOffers2Response>(_GetMigrationOffers2Response_QNAME, GetOffers2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServicesResponse2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOfferServices2Response")
    public JAXBElement<GetServicesResponse2> createGetOfferServices2Response(GetServicesResponse2 value) {
        return new JAXBElement<GetServicesResponse2>(_GetOfferServices2Response_QNAME, GetServicesResponse2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMigrationTariffsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationTariffsResponse")
    public JAXBElement<GetMigrationTariffsResponse> createGetMigrationTariffsResponse(GetMigrationTariffsResponse value) {
        return new JAXBElement<GetMigrationTariffsResponse>(_GetMigrationTariffsResponse_QNAME, GetMigrationTariffsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "product")
    public JAXBElement<ProductInfo> createProduct(ProductInfo value) {
        return new JAXBElement<ProductInfo>(_Product_QNAME, ProductInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionStatusAndOffersResponse2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionStatusAndOffers2Response")
    public JAXBElement<GetRetentionStatusAndOffersResponse2> createGetRetentionStatusAndOffers2Response(GetRetentionStatusAndOffersResponse2 value) {
        return new JAXBElement<GetRetentionStatusAndOffersResponse2>(_GetRetentionStatusAndOffers2Response_QNAME, GetRetentionStatusAndOffersResponse2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveRetentionOffer2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "saveRetentionOffer2")
    public JAXBElement<SaveRetentionOffer2> createSaveRetentionOffer2(SaveRetentionOffer2 value) {
        return new JAXBElement<SaveRetentionOffer2>(_SaveRetentionOffer2_QNAME, SaveRetentionOffer2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Handset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "handset")
    public JAXBElement<Handset> createHandset(Handset value) {
        return new JAXBElement<Handset>(_Handset_QNAME, Handset.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetVanityFee }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getVanityFee")
    public JAXBElement<GetVanityFee> createGetVanityFee(GetVanityFee value) {
        return new JAXBElement<GetVanityFee>(_GetVanityFee_QNAME, GetVanityFee.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Tariff }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "tariff")
    public JAXBElement<Tariff> createTariff(Tariff value) {
        return new JAXBElement<Tariff>(_Tariff_QNAME, Tariff.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProducts }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getProducts")
    public JAXBElement<GetProducts> createGetProducts(GetProducts value) {
        return new JAXBElement<GetProducts>(_GetProducts_QNAME, GetProducts.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOfferDetailsRequest2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOfferDetails2")
    public JAXBElement<GetOfferDetailsRequest2> createGetOfferDetails2(GetOfferDetailsRequest2 value) {
        return new JAXBElement<GetOfferDetailsRequest2>(_GetOfferDetails2_QNAME, GetOfferDetailsRequest2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSavedRetentionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getSavedRetentionResponse")
    public JAXBElement<GetSavedRetentionResponse> createGetSavedRetentionResponse(GetSavedRetentionResponse value) {
        return new JAXBElement<GetSavedRetentionResponse>(_GetSavedRetentionResponse_QNAME, GetSavedRetentionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "faultInfo")
    public JAXBElement<FaultInfo> createFaultInfo(FaultInfo value) {
        return new JAXBElement<FaultInfo>(_FaultInfo_QNAME, FaultInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionStatusAndOffers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionStatusAndOffers")
    public JAXBElement<GetRetentionStatusAndOffers> createGetRetentionStatusAndOffers(GetRetentionStatusAndOffers value) {
        return new JAXBElement<GetRetentionStatusAndOffers>(_GetRetentionStatusAndOffers_QNAME, GetRetentionStatusAndOffers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTariffServices2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getTariffServices2")
    public JAXBElement<GetTariffServices2> createGetTariffServices2(GetTariffServices2 value) {
        return new JAXBElement<GetTariffServices2>(_GetTariffServices2_QNAME, GetTariffServices2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOffers2Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOffers2Response")
    public JAXBElement<GetOffers2Response> createGetOffers2Response(GetOffers2Response value) {
        return new JAXBElement<GetOffers2Response>(_GetOffers2Response_QNAME, GetOffers2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Feature }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "feature")
    public JAXBElement<Feature> createFeature(Feature value) {
        return new JAXBElement<Feature>(_Feature_QNAME, Feature.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductServicingDetailsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getProductServicingDetailsResponse")
    public JAXBElement<GetProductServicingDetailsResponse> createGetProductServicingDetailsResponse(GetProductServicingDetailsResponse value) {
        return new JAXBElement<GetProductServicingDetailsResponse>(_GetProductServicingDetailsResponse_QNAME, GetProductServicingDetailsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getProductsResponse")
    public JAXBElement<GetProductsResponse> createGetProductsResponse(GetProductsResponse value) {
        return new JAXBElement<GetProductsResponse>(_GetProductsResponse_QNAME, GetProductsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCfsInTariffs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getCfsInTariffs")
    public JAXBElement<GetCfsInTariffs> createGetCfsInTariffs(GetCfsInTariffs value) {
        return new JAXBElement<GetCfsInTariffs>(_GetCfsInTariffs_QNAME, GetCfsInTariffs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAdditionalFeesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getAdditionalFeesResponse")
    public JAXBElement<GetAdditionalFeesResponse> createGetAdditionalFeesResponse(GetAdditionalFeesResponse value) {
        return new JAXBElement<GetAdditionalFeesResponse>(_GetAdditionalFeesResponse_QNAME, GetAdditionalFeesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferPromotion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "offerPromotion")
    public JAXBElement<OfferPromotion> createOfferPromotion(OfferPromotion value) {
        return new JAXBElement<OfferPromotion>(_OfferPromotion_QNAME, OfferPromotion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOffersRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOffers")
    public JAXBElement<GetOffersRequest> createGetOffers(GetOffersRequest value) {
        return new JAXBElement<GetOffersRequest>(_GetOffers_QNAME, GetOffersRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCfsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getCfsResponse")
    public JAXBElement<GetCfsResponse> createGetCfsResponse(GetCfsResponse value) {
        return new JAXBElement<GetCfsResponse>(_GetCfsResponse_QNAME, GetCfsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferForGetAllOffers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "offerForGetAllOffers")
    public JAXBElement<OfferForGetAllOffers> createOfferForGetAllOffers(OfferForGetAllOffers value) {
        return new JAXBElement<OfferForGetAllOffers>(_OfferForGetAllOffers_QNAME, OfferForGetAllOffers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTariffsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getTariffsResponse")
    public JAXBElement<GetTariffsResponse> createGetTariffsResponse(GetTariffsResponse value) {
        return new JAXBElement<GetTariffsResponse>(_GetTariffsResponse_QNAME, GetTariffsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionStatusResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionStatusResponse")
    public JAXBElement<GetRetentionStatusResponse> createGetRetentionStatusResponse(GetRetentionStatusResponse value) {
        return new JAXBElement<GetRetentionStatusResponse>(_GetRetentionStatusResponse_QNAME, GetRetentionStatusResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUsageInfoOperationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getUsageInfoResponse")
    public JAXBElement<GetUsageInfoOperationResponse> createGetUsageInfoResponse(GetUsageInfoOperationResponse value) {
        return new JAXBElement<GetUsageInfoOperationResponse>(_GetUsageInfoResponse_QNAME, GetUsageInfoOperationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionStatusAndOffers2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionStatusAndOffers2")
    public JAXBElement<GetRetentionStatusAndOffers2> createGetRetentionStatusAndOffers2(GetRetentionStatusAndOffers2 value) {
        return new JAXBElement<GetRetentionStatusAndOffers2>(_GetRetentionStatusAndOffers2_QNAME, GetRetentionStatusAndOffers2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOffers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOffers2")
    public JAXBElement<GetOffers> createGetOffers2(GetOffers value) {
        return new JAXBElement<GetOffers>(_GetOffers2_QNAME, GetOffers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "offerId")
    public JAXBElement<Long> createOfferId(Long value) {
        return new JAXBElement<Long>(_OfferId_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOfferPhonesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getAllPhonesResponse")
    public JAXBElement<GetOfferPhonesResponse> createGetAllPhonesResponse(GetOfferPhonesResponse value) {
        return new JAXBElement<GetOfferPhonesResponse>(_GetAllPhonesResponse_QNAME, GetOfferPhonesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionStatusAndOffersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionStatusAndOffersResponse")
    public JAXBElement<GetRetentionStatusAndOffersResponse> createGetRetentionStatusAndOffersResponse(GetRetentionStatusAndOffersResponse value) {
        return new JAXBElement<GetRetentionStatusAndOffersResponse>(_GetRetentionStatusAndOffersResponse_QNAME, GetRetentionStatusAndOffersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPhoneInfosResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getPhoneInfosResponse")
    public JAXBElement<GetPhoneInfosResponse> createGetPhoneInfosResponse(GetPhoneInfosResponse value) {
        return new JAXBElement<GetPhoneInfosResponse>(_GetPhoneInfosResponse_QNAME, GetPhoneInfosResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPenaltyWithMaterialCodeOperation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getPenaltyWithMaterialCode")
    public JAXBElement<GetPenaltyWithMaterialCodeOperation> createGetPenaltyWithMaterialCode(GetPenaltyWithMaterialCodeOperation value) {
        return new JAXBElement<GetPenaltyWithMaterialCodeOperation>(_GetPenaltyWithMaterialCode_QNAME, GetPenaltyWithMaterialCodeOperation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUpsellOffers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getUpsellOffers")
    public JAXBElement<GetUpsellOffers> createGetUpsellOffers(GetUpsellOffers value) {
        return new JAXBElement<GetUpsellOffers>(_GetUpsellOffers_QNAME, GetUpsellOffers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetentionOfferOperation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "unlockRetentionOffer")
    public JAXBElement<RetentionOfferOperation> createUnlockRetentionOffer(RetentionOfferOperation value) {
        return new JAXBElement<RetentionOfferOperation>(_UnlockRetentionOffer_QNAME, RetentionOfferOperation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferOperationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "lockRetentionOfferResponse")
    public JAXBElement<OfferOperationResponse> createLockRetentionOfferResponse(OfferOperationResponse value) {
        return new JAXBElement<OfferOperationResponse>(_LockRetentionOfferResponse_QNAME, OfferOperationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCfs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getCfs")
    public JAXBElement<GetCfs> createGetCfs(GetCfs value) {
        return new JAXBElement<GetCfs>(_GetCfs_QNAME, GetCfs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServicesResponse2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getTariffServices2Response")
    public JAXBElement<GetServicesResponse2> createGetTariffServices2Response(GetServicesResponse2 value) {
        return new JAXBElement<GetServicesResponse2>(_GetTariffServices2Response_QNAME, GetServicesResponse2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMaxGroupMembersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMaxGroupMembersResponse")
    public JAXBElement<GetMaxGroupMembersResponse> createGetMaxGroupMembersResponse(GetMaxGroupMembersResponse value) {
        return new JAXBElement<GetMaxGroupMembersResponse>(_GetMaxGroupMembersResponse_QNAME, GetMaxGroupMembersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUsageInfoOperation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getUsageInfo")
    public JAXBElement<GetUsageInfoOperation> createGetUsageInfo(GetUsageInfoOperation value) {
        return new JAXBElement<GetUsageInfoOperation>(_GetUsageInfo_QNAME, GetUsageInfoOperation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOfferProductResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOfferProductResponse")
    public JAXBElement<GetOfferProductResponse> createGetOfferProductResponse(GetOfferProductResponse value) {
        return new JAXBElement<GetOfferProductResponse>(_GetOfferProductResponse_QNAME, GetOfferProductResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CFSServices2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "cfsServices2")
    public JAXBElement<CFSServices2> createCfsServices2(CFSServices2 value) {
        return new JAXBElement<CFSServices2>(_CfsServices2_QNAME, CFSServices2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetentionOfferOperation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "lockRetentionOffer")
    public JAXBElement<RetentionOfferOperation> createLockRetentionOffer(RetentionOfferOperation value) {
        return new JAXBElement<RetentionOfferOperation>(_LockRetentionOffer_QNAME, RetentionOfferOperation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMigrationProcessesWithOffers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationProcessesWithOffers")
    public JAXBElement<GetMigrationProcessesWithOffers> createGetMigrationProcessesWithOffers(GetMigrationProcessesWithOffers value) {
        return new JAXBElement<GetMigrationProcessesWithOffers>(_GetMigrationProcessesWithOffers_QNAME, GetMigrationProcessesWithOffers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMigrationOffers2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationOffers2")
    public JAXBElement<GetMigrationOffers2> createGetMigrationOffers2(GetMigrationOffers2 value) {
        return new JAXBElement<GetMigrationOffers2>(_GetMigrationOffers2_QNAME, GetMigrationOffers2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMaxGroupMembers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMaxGroupMembers")
    public JAXBElement<GetMaxGroupMembers> createGetMaxGroupMembers(GetMaxGroupMembers value) {
        return new JAXBElement<GetMaxGroupMembers>(_GetMaxGroupMembers_QNAME, GetMaxGroupMembers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPenaltyWithMaterialCodeOperationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getPenaltyWithMaterialCodeResponse")
    public JAXBElement<GetPenaltyWithMaterialCodeOperationResponse> createGetPenaltyWithMaterialCodeResponse(GetPenaltyWithMaterialCodeOperationResponse value) {
        return new JAXBElement<GetPenaltyWithMaterialCodeOperationResponse>(_GetPenaltyWithMaterialCodeResponse_QNAME, GetPenaltyWithMaterialCodeOperationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FaultInfoWithRequiredCfs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "faultInfoWithRequiredCfs")
    public JAXBElement<FaultInfoWithRequiredCfs> createFaultInfoWithRequiredCfs(FaultInfoWithRequiredCfs value) {
        return new JAXBElement<FaultInfoWithRequiredCfs>(_FaultInfoWithRequiredCfs_QNAME, FaultInfoWithRequiredCfs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OfferOperationResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "saveRetentionOfferResponse")
    public JAXBElement<OfferOperationResponse> createSaveRetentionOfferResponse(OfferOperationResponse value) {
        return new JAXBElement<OfferOperationResponse>(_SaveRetentionOfferResponse_QNAME, OfferOperationResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMigrationTariffs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationTariffs")
    public JAXBElement<GetMigrationTariffs> createGetMigrationTariffs(GetMigrationTariffs value) {
        return new JAXBElement<GetMigrationTariffs>(_GetMigrationTariffs_QNAME, GetMigrationTariffs.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOffers2Response }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionOffers2Response")
    public JAXBElement<GetOffers2Response> createGetRetentionOffers2Response(GetOffers2Response value) {
        return new JAXBElement<GetOffers2Response>(_GetRetentionOffers2Response_QNAME, GetOffers2Response.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductServicingDetails }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getProductServicingDetails")
    public JAXBElement<GetProductServicingDetails> createGetProductServicingDetails(GetProductServicingDetails value) {
        return new JAXBElement<GetProductServicingDetails>(_GetProductServicingDetails_QNAME, GetProductServicingDetails.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllOffersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getAllOffersResponse")
    public JAXBElement<GetAllOffersResponse> createGetAllOffersResponse(GetAllOffersResponse value) {
        return new JAXBElement<GetAllOffersResponse>(_GetAllOffersResponse_QNAME, GetAllOffersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUpsellOffersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getUpsellOffersResponse")
    public JAXBElement<GetUpsellOffersResponse> createGetUpsellOffersResponse(GetUpsellOffersResponse value) {
        return new JAXBElement<GetUpsellOffersResponse>(_GetUpsellOffersResponse_QNAME, GetUpsellOffersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveRetentionOffer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "saveRetentionOffer")
    public JAXBElement<SaveRetentionOffer> createSaveRetentionOffer(SaveRetentionOffer value) {
        return new JAXBElement<SaveRetentionOffer>(_SaveRetentionOffer_QNAME, SaveRetentionOffer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOfferDetailsResponse2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOfferDetails2Response")
    public JAXBElement<GetOfferDetailsResponse2> createGetOfferDetails2Response(GetOfferDetailsResponse2 value) {
        return new JAXBElement<GetOfferDetailsResponse2>(_GetOfferDetails2Response_QNAME, GetOfferDetailsResponse2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Features }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "features")
    public JAXBElement<Features> createFeatures(Features value) {
        return new JAXBElement<Features>(_Features_QNAME, Features.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Offer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "offer")
    public JAXBElement<Offer> createOffer(Offer value) {
        return new JAXBElement<Offer>(_Offer_QNAME, Offer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSavedRetention }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getSavedRetention")
    public JAXBElement<GetSavedRetention> createGetSavedRetention(GetSavedRetention value) {
        return new JAXBElement<GetSavedRetention>(_GetSavedRetention_QNAME, GetSavedRetention.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSavedRetentionResponse2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getSavedRetention2Response")
    public JAXBElement<GetSavedRetentionResponse2> createGetSavedRetention2Response(GetSavedRetentionResponse2 value) {
        return new JAXBElement<GetSavedRetentionResponse2>(_GetSavedRetention2Response_QNAME, GetSavedRetentionResponse2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServicePoints }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getServicePoints")
    public JAXBElement<GetServicePoints> createGetServicePoints(GetServicePoints value) {
        return new JAXBElement<GetServicePoints>(_GetServicePoints_QNAME, GetServicePoints.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOffersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOffersResponse")
    public JAXBElement<GetOffersResponse> createGetOffersResponse(GetOffersResponse value) {
        return new JAXBElement<GetOffersResponse>(_GetOffersResponse_QNAME, GetOffersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionStatus }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionStatus")
    public JAXBElement<GetRetentionStatus> createGetRetentionStatus(GetRetentionStatus value) {
        return new JAXBElement<GetRetentionStatus>(_GetRetentionStatus_QNAME, GetRetentionStatus.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "tac")
    public JAXBElement<String> createTac(String value) {
        return new JAXBElement<String>(_Tac_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductPenaltyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getProductPenaltyResponse")
    public JAXBElement<GetProductPenaltyResponse> createGetProductPenaltyResponse(GetProductPenaltyResponse value) {
        return new JAXBElement<GetProductPenaltyResponse>(_GetProductPenaltyResponse_QNAME, GetProductPenaltyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServicePoints }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "servicePoints")
    public JAXBElement<ServicePoints> createServicePoints(ServicePoints value) {
        return new JAXBElement<ServicePoints>(_ServicePoints_QNAME, ServicePoints.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FinalPeriodFees }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "finalPeriodFees")
    public JAXBElement<FinalPeriodFees> createFinalPeriodFees(FinalPeriodFees value) {
        return new JAXBElement<FinalPeriodFees>(_FinalPeriodFees_QNAME, FinalPeriodFees.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRetentionOffers2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getRetentionOffers2")
    public JAXBElement<GetRetentionOffers2> createGetRetentionOffers2(GetRetentionOffers2 value) {
        return new JAXBElement<GetRetentionOffers2>(_GetRetentionOffers2_QNAME, GetRetentionOffers2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOfferProduct }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOfferProduct")
    public JAXBElement<GetOfferProduct> createGetOfferProduct(GetOfferProduct value) {
        return new JAXBElement<GetOfferProduct>(_GetOfferProduct_QNAME, GetOfferProduct.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetMigrationProcessesWithOffersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getMigrationProcessesWithOffersResponse")
    public JAXBElement<GetMigrationProcessesWithOffersResponse> createGetMigrationProcessesWithOffersResponse(GetMigrationProcessesWithOffersResponse value) {
        return new JAXBElement<GetMigrationProcessesWithOffersResponse>(_GetMigrationProcessesWithOffersResponse_QNAME, GetMigrationProcessesWithOffersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOfferServices2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getOfferServices2")
    public JAXBElement<GetOfferServices2> createGetOfferServices2(GetOfferServices2 value) {
        return new JAXBElement<GetOfferServices2>(_GetOfferServices2_QNAME, GetOfferServices2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTariffs }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://playmobile.pl/pc/types", name = "getTariffs")
    public JAXBElement<GetTariffs> createGetTariffs(GetTariffs value) {
        return new JAXBElement<GetTariffs>(_GetTariffs_QNAME, GetTariffs.class, null, value);
    }

}
