//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * typ oferty akwizycyjnej, utrzymaniowej i migracyjnej
 * 
 * <p>Java class for Offer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Offer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://playmobile.pl/pc/types}OfferForGetAllOffers">
 *       &lt;attribute name="isVoucherOriginated" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="activationFee" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="isLow" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="isLoyalty" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="returnsAllowed" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="offerDescription" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Offer")
@XmlSeeAlso({
    DetailedOffer2 .class,
    OfferForGetSavedRetention.class
})
public class Offer
    extends OfferForGetAllOffers
{

    @XmlAttribute(name = "isVoucherOriginated")
    protected Boolean isVoucherOriginated;
    @XmlAttribute(name = "activationFee")
    protected BigDecimal activationFee;
    @XmlAttribute(name = "isLow")
    protected Boolean isLow;
    @XmlAttribute(name = "isLoyalty")
    protected Boolean isLoyalty;
    @XmlAttribute(name = "returnsAllowed")
    protected Boolean returnsAllowed;
    @XmlAttribute(name = "offerDescription")
    protected String offerDescription;

    /**
     * Gets the value of the isVoucherOriginated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsVoucherOriginated() {
        return isVoucherOriginated;
    }

    /**
     * Sets the value of the isVoucherOriginated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsVoucherOriginated(Boolean value) {
        this.isVoucherOriginated = value;
    }

    /**
     * Gets the value of the activationFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActivationFee() {
        return activationFee;
    }

    /**
     * Sets the value of the activationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActivationFee(BigDecimal value) {
        this.activationFee = value;
    }

    /**
     * Gets the value of the isLow property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLow() {
        return isLow;
    }

    /**
     * Sets the value of the isLow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLow(Boolean value) {
        this.isLow = value;
    }

    /**
     * Gets the value of the isLoyalty property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsLoyalty() {
        return isLoyalty;
    }

    /**
     * Sets the value of the isLoyalty property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsLoyalty(Boolean value) {
        this.isLoyalty = value;
    }

    /**
     * Gets the value of the returnsAllowed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isReturnsAllowed() {
        return returnsAllowed;
    }

    /**
     * Sets the value of the returnsAllowed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReturnsAllowed(Boolean value) {
        this.returnsAllowed = value;
    }

    /**
     * Gets the value of the offerDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOfferDescription() {
        return offerDescription;
    }

    /**
     * Sets the value of the offerDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOfferDescription(String value) {
        this.offerDescription = value;
    }

}
