//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Informacje na temat poszukiwanych ofert
 * 
 * <p>Java class for OfferFrom complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfferFrom">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="offerFromId" type="{http://playmobile.pl/pc/types}OfferId" />
 *       &lt;attribute name="ccbsTariffFromId" use="required" type="{http://playmobile.pl/pc/types}TariffId" />
 *       &lt;attribute name="ccbsPromotionFromId" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="promotionName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tariffName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfferFrom")
public class OfferFrom {

    @XmlAttribute(name = "offerFromId")
    protected Long offerFromId;
    @XmlAttribute(name = "ccbsTariffFromId", required = true)
    protected String ccbsTariffFromId;
    @XmlAttribute(name = "ccbsPromotionFromId")
    protected Long ccbsPromotionFromId;
    @XmlAttribute(name = "promotionName")
    protected String promotionName;
    @XmlAttribute(name = "tariffName")
    protected String tariffName;

    /**
     * Gets the value of the offerFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOfferFromId() {
        return offerFromId;
    }

    /**
     * Sets the value of the offerFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOfferFromId(Long value) {
        this.offerFromId = value;
    }

    /**
     * Gets the value of the ccbsTariffFromId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsTariffFromId() {
        return ccbsTariffFromId;
    }

    /**
     * Sets the value of the ccbsTariffFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsTariffFromId(String value) {
        this.ccbsTariffFromId = value;
    }

    /**
     * Gets the value of the ccbsPromotionFromId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCcbsPromotionFromId() {
        return ccbsPromotionFromId;
    }

    /**
     * Sets the value of the ccbsPromotionFromId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCcbsPromotionFromId(Long value) {
        this.ccbsPromotionFromId = value;
    }

    /**
     * Gets the value of the promotionName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPromotionName() {
        return promotionName;
    }

    /**
     * Sets the value of the promotionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPromotionName(String value) {
        this.promotionName = value;
    }

    /**
     * Gets the value of the tariffName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTariffName() {
        return tariffName;
    }

    /**
     * Sets the value of the tariffName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTariffName(String value) {
        this.tariffName = value;
    }

}
