//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * typ promocji powi¹zanej z ofert¹
 * 
 * <p>Java class for OfferPromotion complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OfferPromotion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ccbsPromotionId" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="isRollover" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="specialOffer" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OfferPromotion")
public class OfferPromotion {

    @XmlAttribute(name = "ccbsPromotionId", required = true)
    protected String ccbsPromotionId;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "isRollover")
    protected Boolean isRollover;
    @XmlAttribute(name = "specialOffer")
    protected String specialOffer;

    /**
     * Gets the value of the ccbsPromotionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCcbsPromotionId() {
        return ccbsPromotionId;
    }

    /**
     * Sets the value of the ccbsPromotionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCcbsPromotionId(String value) {
        this.ccbsPromotionId = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isRollover property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsRollover() {
        return isRollover;
    }

    /**
     * Sets the value of the isRollover property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsRollover(Boolean value) {
        this.isRollover = value;
    }

    /**
     * Gets the value of the specialOffer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialOffer() {
        return specialOffer;
    }

    /**
     * Sets the value of the specialOffer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialOffer(String value) {
        this.specialOffer = value;
    }

}
