//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ParameterType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ParameterType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="msisdn"/>
 *     &lt;enumeration value="number"/>
 *     &lt;enumeration value="string"/>
 *     &lt;enumeration value="integer"/>
 *     &lt;enumeration value="date"/>
 *     &lt;enumeration value="msisdnplay"/>
 *     &lt;enumeration value="msisdnplst"/>
 *     &lt;enumeration value="ratekeyut5"/>
 *     &lt;enumeration value="ratekeyut6"/>
 *     &lt;enumeration value="deactdatem"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ParameterType")
@XmlEnum
public enum ParameterType {

    @XmlEnumValue("msisdn")
    MSISDN("msisdn"),
    @XmlEnumValue("number")
    NUMBER("number"),
    @XmlEnumValue("string")
    STRING("string"),
    @XmlEnumValue("integer")
    INTEGER("integer"),
    @XmlEnumValue("date")
    DATE("date"),
    @XmlEnumValue("msisdnplay")
    MSISDNPLAY("msisdnplay"),
    @XmlEnumValue("msisdnplst")
    MSISDNPLST("msisdnplst"),
    @XmlEnumValue("ratekeyut5")
    RATEKEYUT_5("ratekeyut5"),
    @XmlEnumValue("ratekeyut6")
    RATEKEYUT_6("ratekeyut6"),
    @XmlEnumValue("deactdatem")
    DEACTDATEM("deactdatem");
    private final String value;

    ParameterType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ParameterType fromValue(String v) {
        for (ParameterType c: ParameterType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
