//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * Wymagany cfs, zawiera id cfs oraz jego nazwê
 * 
 * <p>Java class for RequiredCfs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RequiredCfs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="cfsId" use="required" type="{http://playmobile.pl/pc/types}IdType" />
 *       &lt;attribute name="cfsName" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RequiredCfs")
public class RequiredCfs {

    @XmlAttribute(name = "cfsId", required = true)
    protected long cfsId;
    @XmlAttribute(name = "cfsName", required = true)
    protected String cfsName;

    /**
     * Gets the value of the cfsId property.
     * 
     */
    public long getCfsId() {
        return cfsId;
    }

    /**
     * Sets the value of the cfsId property.
     * 
     */
    public void setCfsId(long value) {
        this.cfsId = value;
    }

    /**
     * Gets the value of the cfsName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCfsName() {
        return cfsName;
    }

    /**
     * Sets the value of the cfsName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCfsName(String value) {
        this.cfsName = value;
    }

}
