//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Status oferty utrzymaniowej
 * 
 * <p>Java class for RetentionOfferStatus complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RetentionOfferStatus">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="status" use="required" type="{http://playmobile.pl/pc/types}RetentionStatus" />
 *       &lt;attribute name="whoChanged" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="modified" type="{http://playmobile.pl/pc/types}Date" />
 *       &lt;attribute name="validTo" type="{http://playmobile.pl/pc/types}Date" />
 *       &lt;attribute name="salesChannel" type="{http://playmobile.pl/pc/types}SalesChannel" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RetentionOfferStatus")
public class RetentionOfferStatus {

    @XmlAttribute(name = "status", required = true)
    protected RetentionStatus status;
    @XmlAttribute(name = "whoChanged")
    protected String whoChanged;
    @XmlAttribute(name = "modified")
    protected XMLGregorianCalendar modified;
    @XmlAttribute(name = "validTo")
    protected XMLGregorianCalendar validTo;
    @XmlAttribute(name = "salesChannel")
    protected SalesChannel salesChannel;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link RetentionStatus }
     *     
     */
    public RetentionStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link RetentionStatus }
     *     
     */
    public void setStatus(RetentionStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the whoChanged property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWhoChanged() {
        return whoChanged;
    }

    /**
     * Sets the value of the whoChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWhoChanged(String value) {
        this.whoChanged = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setModified(XMLGregorianCalendar value) {
        this.modified = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the salesChannel property.
     * 
     * @return
     *     possible object is
     *     {@link SalesChannel }
     *     
     */
    public SalesChannel getSalesChannel() {
        return salesChannel;
    }

    /**
     * Sets the value of the salesChannel property.
     * 
     * @param value
     *     allowed object is
     *     {@link SalesChannel }
     *     
     */
    public void setSalesChannel(SalesChannel value) {
        this.salesChannel = value;
    }

}
