//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.28 at 10:33:06 AM CEST 
//


package rafal.kod.jaxb;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RFSComponentAttributes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RFSComponentAttributes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="componentParameters" type="{http://playmobile.pl/pc/types}RFSComponentParameters" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="periodFee" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="activationFee" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="groupId" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="isBundle" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="freeSeconds" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="smsMms" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="promotionBalance" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="data" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="data2" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="valuePack" type="{http://playmobile.pl/pc/types}Amount" />
 *       &lt;attribute name="freeLeFreeSeconds" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="hiddenBalance9" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="balance10" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RFSComponentAttributes", propOrder = {
    "componentParameters"
})
public class RFSComponentAttributes {

    protected List<RFSComponentParameters> componentParameters;
    @XmlAttribute(name = "periodFee")
    protected BigDecimal periodFee;
    @XmlAttribute(name = "activationFee")
    protected BigDecimal activationFee;
    @XmlAttribute(name = "groupId")
    @XmlSchemaType(name = "unsignedInt")
    protected Long groupId;
    @XmlAttribute(name = "isBundle")
    protected Boolean isBundle;
    @XmlAttribute(name = "freeSeconds")
    @XmlSchemaType(name = "unsignedInt")
    protected Long freeSeconds;
    @XmlAttribute(name = "smsMms")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger smsMms;
    @XmlAttribute(name = "promotionBalance")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger promotionBalance;
    @XmlAttribute(name = "data")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger data;
    @XmlAttribute(name = "data2")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger data2;
    @XmlAttribute(name = "valuePack")
    protected BigDecimal valuePack;
    @XmlAttribute(name = "freeLeFreeSeconds")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger freeLeFreeSeconds;
    @XmlAttribute(name = "hiddenBalance9")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger hiddenBalance9;
    @XmlAttribute(name = "balance10")
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger balance10;

    /**
     * Gets the value of the componentParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the componentParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getComponentParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RFSComponentParameters }
     * 
     * 
     */
    public List<RFSComponentParameters> getComponentParameters() {
        if (componentParameters == null) {
            componentParameters = new ArrayList<RFSComponentParameters>();
        }
        return this.componentParameters;
    }

    /**
     * Gets the value of the periodFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPeriodFee() {
        return periodFee;
    }

    /**
     * Sets the value of the periodFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPeriodFee(BigDecimal value) {
        this.periodFee = value;
    }

    /**
     * Gets the value of the activationFee property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getActivationFee() {
        return activationFee;
    }

    /**
     * Sets the value of the activationFee property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setActivationFee(BigDecimal value) {
        this.activationFee = value;
    }

    /**
     * Gets the value of the groupId property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getGroupId() {
        return groupId;
    }

    /**
     * Sets the value of the groupId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setGroupId(Long value) {
        this.groupId = value;
    }

    /**
     * Gets the value of the isBundle property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBundle() {
        return isBundle;
    }

    /**
     * Sets the value of the isBundle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBundle(Boolean value) {
        this.isBundle = value;
    }

    /**
     * Gets the value of the freeSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getFreeSeconds() {
        return freeSeconds;
    }

    /**
     * Sets the value of the freeSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setFreeSeconds(Long value) {
        this.freeSeconds = value;
    }

    /**
     * Gets the value of the smsMms property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSmsMms() {
        return smsMms;
    }

    /**
     * Sets the value of the smsMms property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSmsMms(BigInteger value) {
        this.smsMms = value;
    }

    /**
     * Gets the value of the promotionBalance property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPromotionBalance() {
        return promotionBalance;
    }

    /**
     * Sets the value of the promotionBalance property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPromotionBalance(BigInteger value) {
        this.promotionBalance = value;
    }

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setData(BigInteger value) {
        this.data = value;
    }

    /**
     * Gets the value of the data2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getData2() {
        return data2;
    }

    /**
     * Sets the value of the data2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setData2(BigInteger value) {
        this.data2 = value;
    }

    /**
     * Gets the value of the valuePack property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValuePack() {
        return valuePack;
    }

    /**
     * Sets the value of the valuePack property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValuePack(BigDecimal value) {
        this.valuePack = value;
    }

    /**
     * Gets the value of the freeLeFreeSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFreeLeFreeSeconds() {
        return freeLeFreeSeconds;
    }

    /**
     * Sets the value of the freeLeFreeSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFreeLeFreeSeconds(BigInteger value) {
        this.freeLeFreeSeconds = value;
    }

    /**
     * Gets the value of the hiddenBalance9 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getHiddenBalance9() {
        return hiddenBalance9;
    }

    /**
     * Sets the value of the hiddenBalance9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setHiddenBalance9(BigInteger value) {
        this.hiddenBalance9 = value;
    }

    /**
     * Gets the value of the balance10 property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBalance10() {
        return balance10;
    }

    /**
     * Sets the value of the balance10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBalance10(BigInteger value) {
        this.balance10 = value;
    }

}
